### ISSUE TITLE
kafka-connect-druid : java.lang.ClassCastException: No casts succeeded for: class java.lang.String

### ISSUE THREAD

**Issue by austindsouza** [datamountaineer/stream-reactor#113]
Hi,

I am trying to get the data from Kafka topic and sinking it to Druid dataset using kafka-connect-druid connector, while doing this I am getting error.

==============================================
My configuration for druid-sink is like this

name=druid-sink
connector.class=com.datamountaineer.streamreactor.connect.druid.DruidSinkConnector
connect.druid.sink.datasource.name=pageviews
connect.druid.sink.config.file=/home/tg1/Development/config/druid-sink.properties
connect.druid.sink.fields=time=time,url=url,user=user,latencyMs=latencyMs 

===============================================
I am putting the data to kafka topic using avro console consumer

kafka-avro-console-producer --broker-list 10.10.1.34:9092 --topic test_druid --property value.schema='{"type":"record","name":"myrecord","fields":[{"name":"time","type":"date"},{"name":"url", "type": "string"},{"name":"user", "type": "string"},{"name":"latencyMs", "type": "int"}]}'
{"time": "2017-01-14T11:35:08Z", "url": "/foo/bar", "user": "bob", "latencyMs": 35}
{"time": "2017-01-14T11:45:09Z", "url": "/", "user": "alice", "latencyMs": 15}
{"time": "2017-01-14T11:50:10Z", "url": "/foo/bar", "user": "bob", "latencyMs": 55}

===============================================

Error I am getting is:

name=druid-sink
connector.class=com.datamountaineer.streamreactor.connect.druid.DruidSinkConnector
connect.druid.sink.datasource.name=pageviews
connect.druid.sink.config.file=/home/tg1/Development/Aeverie_Softwares/Confluent-Source/schema-registry-3.0.0/config/druid-sink.properties
connect.druid.sink.fields=time=time,url=url,user=user,latencyMs=latencyMs
,Map(test_druid -> StructFieldsExtractor(false,Map())))
       (com.datamountaineer.streamreactor.connect.druid.DruidSinkTask:63)

[2017-01-14 12:43:40,368] ERROR Task druid-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
java.lang.ClassCastException: No casts succeeded for: class java.lang.String
	at com.metamx.common.scala.untyped$.tryCasts(untyped.scala:78)
	at com.metamx.common.scala.untyped$.dict(untyped.scala:46)
	at com.metamx.tranquility.config.TranquilityConfig$$anonfun$2.apply(TranquilityConfig.scala:63)
	at com.metamx.tranquility.config.TranquilityConfig$$anonfun$2.apply(TranquilityConfig.scala:62)
	at com.metamx.common.scala.Predef$FinallyOps$$anonfun$withFinally$1.apply(Predef.scala:56)
	at com.metamx.common.scala.Predef$FinallyOps$$anonfun$withFinally$1.apply(Predef.scala:56)
	at com.metamx.tranquility.config.TranquilityConfig$.read(TranquilityConfig.scala:62)
	at com.metamx.tranquility.config.TranquilityConfig$.read(TranquilityConfig.scala:93)
	at com.datamountaineer.streamreactor.connect.druid.writer.DruidDbWriter.<init>(DruidDbWriter.scala:42)
	at com.datamountaineer.streamreactor.connect.druid.DruidSinkTask.start(DruidSinkTask.scala:67)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:208)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Can you help me what is wrong.
Thanks in advance.

**Comment by stheppi** [comment]
@austindsouza 
 Your schema is wrong. there is no type Date in avro. The support for it comes via logical types. the ones available are timestamp, date, decimal and time. in your case date is provided as Int and the type is enhance with extra tags something like:

{
"name": "last_modified_date",
"type": {
"type": "int",
"connect.version": 1,
"connect.name": "org.apache.kafka.connect.data.Date"
}
}

once the latest PR makes it to master we will throw an error if such un-recognized type is passed. I think if you provide your type the value is considered string. therefore as you try to push string to date it will throw an exception.

**Comment by amoussoubaruch** [comment]
Hi @stheppi 

I'm using kafka connector for druid and i have the same problem that as mentioned above. But I tried connector with influxDb and it's work fine. With druid i have this error 

`connect.progress.enabled=true
name=druid-sink
connector.class=com.datamountaineer.streamreactor.connect.druid.DruidSinkConnector
max.tasks=1
topics=MyTopics
connect.druid.sink.config.file=druid-sink.properties
transforms=landoopSql
transforms.landoopSql.type=com.landoop.connect.sql.Transformation
transforms.landoopSql.connect.transforms.sql.value=SELECT body.field1, body.field2 FROM MyTopics
connect.druid.sink.kcql=INSERT INTO MyTable SELECT * FROM MyTopics
,Map(jcd_PlayerMetric -> StructFieldsExtractor(false,Map())))
       (com.datamountaineer.streamreactor.connect.druid.DruidSinkTask:61)
[2017-07-13 17:17:36,390] ERROR Task druid-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:141)
java.lang.ClassCastException: No casts succeeded for: class java.lang.String
	at com.metamx.common.scala.untyped$.tryCasts(untyped.scala:78)
	at com.metamx.common.scala.untyped$.dict(untyped.scala:46)
	at com.metamx.tranquility.config.TranquilityConfig$$anonfun$2.apply(TranquilityConfig.scala:63)
	at com.metamx.tranquility.config.TranquilityConfig$$anonfun$2.apply(TranquilityConfig.scala:62)
	at com.metamx.common.scala.Predef$FinallyOps$$anonfun$withFinally$1.apply(Predef.scala:56)
	at com.metamx.common.scala.Predef$FinallyOps$$anonfun$withFinally$1.apply(Predef.scala:56)
	at com.metamx.tranquility.config.TranquilityConfig$.read(TranquilityConfig.scala:62)
	at com.metamx.tranquility.config.TranquilityConfig$.read(TranquilityConfig.scala:93)
	at com.datamountaineer.streamreactor.connect.druid.writer.DruidDbWriter.<init>(DruidDbWriter.scala:40)
	at com.datamountaineer.streamreactor.connect.druid.DruidSinkTask.start(DruidSinkTask.scala:65)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:231)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:145)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-07-13 17:17:36,401] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:142)
[2017-07-13 17:17:36,402] INFO Stopping Hbase sink. (com.datamountaineer.streamreactor.connect.druid.DruidSinkTask:85)
`

It's same schema registry i use with influxDb and i hadn't any error. 
Can you please enlighten me? 

Thanks

**Comment by LihaoLixue** [comment]
@amoussoubaruch Hello,amoussoubaruch. I am starting to study what kafka connect send data to druid,but I meet some troubles now.Do you show the file of ***.properties to me?

**Comment by amoussoubaruch** [comment]
hi @LihaoLixue 

You need two files : 

1. connect-avro-standalone.properties 

`bootstrap.servers=broker1:9092,broker1:9092

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=io.confluent.connect.avro.AvroConverter

value.converter.schema.registry.url=http://.....
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://.....
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://.....

internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false

# Local storage file for offset data
offset.storage.file.filename=specify your own directory `

2. druid-source.properties


`connect.progress.enabled=true
name=druid-sink
connector.class=com.datamountaineer.streamreactor.connect.druid.DruidSinkConnector
max.tasks=1
topics=Your_topic
connect.druid.sink.config.file=/root/druid-source.properties
transforms=landoopSql
transforms.landoopSql.type=com.landoop.connect.sql.Transformation
transforms.landoopSql.connect.transforms.sql.value=SELECT body.playerid, body.hostname, body.category, body.name FROM Your_topic
connect.druid.sink.kcql=INSERT INTO you_Druid_Datasource SELECT * FROM Your_topic

`
