### ISSUE TITLE
jms-sink is failing with bellow error because of org.apache.activemq.ActiveMQConnectionFactory not getting loaded

### ISSUE THREAD

**Issue by shiva404** [datamountaineer/stream-reactor#138]
```
[2017-03-09 15:38:43,246] ERROR Task jms-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:141)
io.confluent.common.config.ConfigException: $clazz can not be loaded
	at com.datamountaineer.streamreactor.connect.jms.sink.config.JMSSettings$$anonfun$5.apply(JMSSettings.scala:67)
	at com.datamountaineer.streamreactor.connect.jms.sink.config.JMSSettings$$anonfun$5.apply(JMSSettings.scala:67)
	at scala.util.Try.getOrElse(Try.scala:79)
	at com.datamountaineer.streamreactor.connect.jms.sink.config.JMSSettings$.apply(JMSSettings.scala:67)
	at com.datamountaineer.streamreactor.connect.jms.JMSSinkTask.start(JMSSinkTask.scala:76)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:231)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:145)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by shiva404** [comment]
After adding activemq-all jar to CLASSPATH resolved the issue.

Thanks
Shiv
