### ISSUE TITLE
NullPointerException in CassandraSourceConnector

### ISSUE THREAD

**Issue by ccl0326** [datamountaineer/stream-reactor#144]
2017-03-17 14:51:27,984 ERROR org.apache.kafka.connect.runtime.WorkerTask: Task ActivityCassandraSourceConnector-0 threw an uncaught and unrecoverable exception
java.lang.NullPointerException
        at org.apache.kafka.connect.connector.ConnectRecord.hashCode(ConnectRecord.java:128)
        at org.apache.kafka.connect.source.SourceRecord.hashCode(SourceRecord.java:109)
        at scala.runtime.ScalaRunTime$.hash(ScalaRunTime.scala:206)
        at scala.collection.immutable.HashSet.elemHashCode(HashSet.scala:177)
        at scala.collection.immutable.HashSet.computeHash(HashSet.scala:186)
        at scala.collection.immutable.HashSet.$plus(HashSet.scala:84)
        at scala.collection.immutable.HashSet.$plus(HashSet.scala:87)
        at scala.collection.immutable.Set$Set4.$plus(Set.scala:190)
        at scala.collection.immutable.Set$Set4.$plus(Set.scala:184)
        at scala.collection.mutable.SetBuilder.$plus$eq(SetBuilder.scala:22)
        at scala.collection.mutable.SetBuilder.$plus$eq(SetBuilder.scala:20)
        at scala.collection.generic.Growable$class.loop$1(Growable.scala:53)
        at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:57)
        at scala.collection.mutable.SetBuilder.$plus$plus$eq(SetBuilder.scala:20)
        at scala.collection.generic.GenericTraversableTemplate$$anonfun$flatten$1.apply(GenericTraversableTemplate.scala:172)
        at scala.collection.generic.GenericTraversableTemplate$$anonfun$flatten$1.apply(GenericTraversableTemplate.scala:171)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
        at scala.collection.generic.GenericTraversableTemplate$class.flatten(GenericTraversableTemplate.scala:171)
        at scala.collection.AbstractTraversable.flatten(Traversable.scala:104)
        at com.datamountaineer.streamreactor.connect.cassandra.source.CassandraSourceTask.poll(CassandraSourceTask.scala:115)
        at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:155)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by andrewstevenson** [comment]
@ccl0326 You will need to provide more context than this. What version? What is you Connect cluster config? What is your Source Connector Config? Can you supply the start up log?

**Comment by ccl0326** [comment]
version is 0.24

connect config
```
connect.log4j.dir=/var/log/fastdata
connections.max.idle.ms=540000
heartbeat.interval.ms=3000
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter.schemas.enable=false
kerberos.auth.enable=false
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://localhost:8081
metadata.max.age.ms=300000
metrics.num.samples=2
metrics.sample.window.ms=30000
offset.flush.interval.ms=60000
offset.flush.timeout.ms=5000
receive.buffer.bytes=65536
reconnect.backoff.ms=50
request.timeout.ms=40000
rest.port=8085
retry.backoff.ms=100
security.protocol=PLAINTEXT
send.buffer.bytes=131072
session.timeout.ms=30000
task.shutdown.graceful.timeout.ms=5000
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://localhost:8081
worker.sync.timeout.ms=3000
worker.unsync.backoff.ms=300000
#ssl.configs={{SSL_CONFIGS}}
sasl.kerberos.service.name=kafka
producer.security.protocol=PLAINTEXT
#producer_ssl.configs={{PRODUCER_SSL_CONFIGS}}
consumer.security.protocol=PLAINTEXT
#consumer.ssl.configs={{CONSUMER_SSL_CONFIGS}}
offset.storage.topic=connect-offsets
status.storage.topic=connect-status
config.storage.topic=connect-configs
group.id=connect-cluster
zookeeper.connect=prd-offline-002.prd.leyantech.com:2181,prd-offline-003.prd.leyantech.com:2181,prd-offline-004.prd.leyantech.com:2181/fastdata
bootstrap.servers=PLAINTEXT://prd-offline-002.prd.leyantech.com:9092,PLAINTEXT://prd-offline-003.prd.leyantech.com:9092,PLAINTEXT://prd-offline-004.prd.leyantech.com:9092
```

**Comment by ccl0326** [comment]
connector config:
```
{
  "connector.class": "com.datamountaineer.streamreactor.connect.cassandra.source.CassandraSourceConnector",
  "connect.cassandra.import.mode": "incremental",
  "connect.cassandra.consistency.level": "ONE",
  "connect.cassandra.key.space": "activity",
  "tasks.max": "1",
  "connect.cassandra.ssl.client.cert.auth": "false",
  "connect.cassandra.import.poll.interval": "60000",
  "connect.cassandra.username": "",
  "connect.cassandra.contact.points": "addr",
  "connect.cassandra.port": "9042",
  "connect.cassandra.source.task.buffer.size": "100000",
  "connect.cassandra.retry.interval": "60000",
  "value.converter": "io.confluent.connect.avro.AvroConverter",
  "connect.cassandra.assigned.tables": "activity_new",
  "key.converter": "io.confluent.connect.avro.AvroConverter",
  "connect.cassandra.import.source.allow.filtering": "true",
  "topics": "Activity_CassandraSourceConnector",
  "connect.cassandra.password": "",
  "connect.cassandra.error.policy": "THROW",
  "value.converter.schema.registry.url": "http://localhost:8081",
  "connect.cassandra.source.task.batch.size": "100",
  "name": "ActivityCassandraSourceConnector",
  "connect.cassandra.source.kcql": "INSERT INTO Activity_CassandraSourceConnector SELECT * FROM activity_new PK timestamp",
  "key.converter.schema.registry.url": "http://localhost:8081",
  "connect.cassandra.max.retires": "20"
}
```

**Comment by ccl0326** [comment]
logs before exception,
```
2017-03-17 14:51:27,951 INFO com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader: Storing offset 2017-03-17 11:02:43.895Z
2017-03-17 14:51:27,951 INFO com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader: Storing offset 2017-03-17 11:02:44.778Z
2017-03-17 14:51:27,951 INFO com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader: Storing offset 2017-03-17 11:02:45.305Z
2017-03-17 14:51:27,951 INFO com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader: Storing offset 2017-03-17 11:02:45.331Z
2017-03-17 14:51:27,951 INFO com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader: Storing offset 2017-03-17 11:02:46.417Z
2017-03-17 14:51:27,951 INFO com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader: Storing offset 2017-03-17 11:02:46.551Z
2017-03-17 14:51:27,951 INFO com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader: Storing offset 2017-03-17 11:02:47.644Z
2017-03-17 14:51:27,951 INFO com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader: Storing offset 2017-03-17 11:02:47.884Z
2017-03-17 14:51:27,951 INFO com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader: Storing offset 2017-03-17 11:02:49.240Z
2017-03-17 14:51:27,951 INFO com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader: Storing offset 2017-03-17 11:02:49.642Z
2017-03-17 14:51:27,952 INFO com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader: Storing offset 2017-03-17 11:02:51.515Z
2017-03-17 14:51:27,952 INFO com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader: Storing offset 2017-03-17 11:02:52.687Z
2017-03-17 14:51:27,952 INFO com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader: Storing offset 2017-03-17 11:02:53.656Z
2017-03-17 14:51:27,952 INFO com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader: Storing offset 2017-03-17 11:02:53.662Z
2017-03-17 14:51:27,952 INFO com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader: Storing offset 2017-03-17 11:02:54.178Z
2017-03-17 14:51:27,952 INFO com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader: Storing offset 2017-03-17 11:02:54.222Z
2017-03-17 14:51:27,952 INFO com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader: Storing offset 2017-03-17 11:02:54.696Z
2017-03-17 14:51:27,952 INFO com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader: Storing offset 2017-03-17 11:02:55.417Z
2017-03-17 14:51:27,952 INFO com.datamountaineer.streamreactor.connect.cassandra.source.CassandraTableReader: Storing offset 2017-03-17 11:02:56.293Z
2017-03-17 14:51:27,984 INFO org.apache.kafka.connect.runtime.WorkerSourceTask: Finished WorkerSourceTask{id=ActivityCassandraSourceConnector-0} commitOffsets successfully in 7 ms
```

**Comment by andrewstevenson** [comment]
@ccl0326 which release version?

**Comment by ccl0326** [comment]
@andrewstevenson 0.24

**Comment by andrewstevenson** [comment]
@ccl0326  which version of confluent and kafka?

**Comment by andrewstevenson** [comment]
@ccl0326 you're hitting this bug in Connect https://issues.apache.org/jira/browse/KAFKA-4334

**Comment by ccl0326** [comment]
kafka version is 0.10.1-IV2.
confluent version is 3.1.2.

**Comment by andrewstevenson** [comment]
it's fixed in Kafka 0.10.2 and Confluent 3.2

**Comment by ccl0326** [comment]
@andrewstevenson thanks, i will upgrade them.

**Comment by andrewstevenson** [comment]
The brokers are backwards compatible so the 0.2.4 stream reactor release should work. We'll be release 0.2.5 soon with Confluent 3.2 support.
