### ISSUE TITLE
cli.sh execution problems

### ISSUE THREAD

**Issue by matesio** [datamountaineer/stream-reactor#146]
error could not found jar file
/stream-reactor/bin/../build/libs/kafka-connect-cli-@@CLI_VERSION@@-all.jar

i tried downloading cli1.0 and executed java -jar cli1.0.jar
but it gave me error
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: scala/Option
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)

**Comment by andrewstevenson** [comment]
@matesio In the build.gradle we replace the @@CLI_VERSION@@ when building so you aren't meant to call this script.

Where did you download the cli from? Try this

`wget https://github.com/datamountaineer/kafka-connect-tools/releases/download/v1.0/kafka-connect-cli-1.0-all.jar`
