### ISSUE TITLE
druid-sink.properties inside config package is not working

### ISSUE THREAD

**Issue by mhshimul** [datamountaineer/stream-reactor#161]
I believe something has changed inside code for druid-sink.properties as I can see there is a new property connect.druid.sink.kcql inside DruidSinkConfig file. Need a working properties file sample.

**Comment by mhshimul** [comment]
I believe something has changed inside code for druid-sink.properties as I can see there is a new property connect.druid.sink.kcql inside DruidSinkConfig file. Need a working properties file sample.

**Comment by andrewstevenson** [comment]
@mhshimul Try this, note that this sink hasn't been properly tested so let us know how you get on, contributions also welcome!

```name=druid-sink
connector.class=com.datamountaineer.streamreactor.connect.druid.DruidSinkConnector
connect.druid.sink.config.file=my_druid_config_file
connect.druid.sink.kcql=INSERT INTO wikipedia SELECT page, robot AS bot, country FROM test```

**Comment by mhshimul** [comment]
Now after setting this property, getting following exception

```
[2017-04-15 01:36:25,661] ERROR Task druid-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:141)
java.lang.ExceptionInInitializerError
	at com.metamx.tranquility.druid.DruidBeams$.<init>(DruidBeams.scala:107)
	at com.metamx.tranquility.druid.DruidBeams$.<clinit>(DruidBeams.scala)
	at com.datamountaineer.streamreactor.connect.druid.writer.DruidDbWriter$$anonfun$1.apply(DruidDbWriter.scala:44)
	at com.datamountaineer.streamreactor.connect.druid.writer.DruidDbWriter$$anonfun$1.apply(DruidDbWriter.scala:42)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.datamountaineer.streamreactor.connect.druid.writer.DruidDbWriter.<init>(DruidDbWriter.scala:41)
	at com.datamountaineer.streamreactor.connect.druid.DruidSinkTask.start(DruidSinkTask.scala:65)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:231)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:145)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Incompatible Jackson version: 2.8.5
	at com.fasterxml.jackson.module.scala.JacksonModule$class.setupModule(JacksonModule.scala:64)
	at com.fasterxml.jackson.module.scala.DefaultScalaModule.setupModule(DefaultScalaModule.scala:19)
	at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:745)
	at com.metamx.common.scala.Jackson$$anonfun$newObjectMapper$1.apply(Jackson.scala:70)
	at com.metamx.common.scala.Jackson$$anonfun$newObjectMapper$1.apply(Jackson.scala:68)
	at com.metamx.common.scala.Predef$EffectOps.withEffect(Predef.scala:44)
	at com.metamx.common.scala.Jackson$class.newObjectMapper(Jackson.scala:67)
	at com.metamx.common.scala.Jackson$.newObjectMapper(Jackson.scala:10)
	at com.metamx.common.scala.Jackson$class.newObjectMapper(Jackson.scala:64)
	at com.metamx.common.scala.Jackson$.newObjectMapper(Jackson.scala:10)
	at com.metamx.common.scala.Jackson$class.$init$(Jackson.scala:14)
	at com.metamx.common.scala.Jackson$.<init>(Jackson.scala:10)
	at com.metamx.common.scala.Jackson$.<clinit>(Jackson.scala)
	... 20 more

```
