### ISSUE TITLE
Error decoding JSON for timestamp equal to 0

### ISSUE THREAD

**Issue by jnguyenx** [datamountaineer/stream-reactor#180]
I'm having a weird issue with the Kafka Cassandra sink. When a timestamp field is equal to 0, the field is decoded to Integer instead of Long.

The Cassandra schema:
```
CREATE TABLE foo.bar (
myfield timestamp,
PRIMARY KEY (myfield)
);
```

The Avro schema from the schema registry:
```
{
  "namespace": "foo.bar",
  "type": "record",
  "name": "FooBar",
  "fields": [
    {
      "name": "myfield",
      "type": [
        "null",
        "long"
      ],
      "logicalType": "timestamp-millis"
    }
]
}
```

And the JSON from the Kafka stream:
```
{"myfield":{"long":0}}
```

However when `myfield` has a value different from 0, it works as expected.

I'm a new user of those tools, so I may have made an obvious mistake.

Here's the stacktrace from the Kafka connect logs: 
```
ERROR There was an error inserting the records Error decoding JSON value for myfield: Expected a long or a datestring representation of a timestamp value, but got a Integer: 0 (com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter:155)
com.datastax.driver.core.exceptions.InvalidQueryException: Error decoding JSON value for myfield: Expected a long or a datestring representation of a timestamp value, but got a Integer: 0
        at com.datastax.driver.core.exceptions.InvalidQueryException.copy(InvalidQueryException.java:50)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
        at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:63)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$3$$anonfun$apply$1.apply$mcV$sp(CassandraJsonWriter.scala:136)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$3$$anonfun$apply$1.apply(CassandraJsonWriter.scala:130)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$3$$anonfun$apply$1.apply(CassandraJsonWriter.scala:130)
        at com.datamountaineer.streamreactor.connect.concurrent.ExecutorExtension$RunnableWrapper$$anon$1.run(ExecutorExtension.scala:30)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Error decoding JSON value for myfield: Expected a long or a datestring representation of a timestamp value, but got a Integer: 0
        at com.datastax.driver.core.Responses$Error.asException(Responses.java:136)
        at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179)
        at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:184)
        at com.datastax.driver.core.RequestHandler.access$2500(RequestHandler.java:43)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:798)
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:617)
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1005)
        at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:928)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
        ... 1 more

```

**Comment by stheppi** [comment]
@jnguyenx ,
   We will look into this. But looking at the stacktrace is Cassandra driver for json insert. We pass the json to Cassandra and they will do the parsing and the inserts. Looks like there is a problem there. What Cassandra version are you using?

**Comment by jnguyenx** [comment]
I'm using Cassandra 3.7.0 at the moment.

Thanks!

**Comment by jnguyenx** [comment]
I've checked with 3.10 and directly from the shell, I got the same issue.

```
cqlsh:foo> INSERT INTO bar JSON '{"myfield":2147483647}';
InvalidRequest: Error from server: code=2200 [Invalid query] message="Error decoding JSON value for myfield: Expected a long or a datestring representation of a timestamp value, but got a Integer: 2147483647"
cqlsh:foo> INSERT INTO bar JSON '{"myfield":2147483648}';
cqlsh:foo> 
```

Do you have a way to copy this ticket over to Cassandra's Jira?

**Comment by andrewstevenson** [comment]
Hi Jeremy,

I’m afraid we don’t.

Regards,

Andrew

**Comment by jnguyenx** [comment]
I've created an issue on their Jira. Thanks for the help!
https://issues.apache.org/jira/browse/CASSANDRA-13535

**Comment by andrewstevenson** [comment]
Thanks for the heads up, if you like you can join our slack channel here<https://slackpass.io/datamountaineers>. Anything else we can help with?

**Comment by jnguyenx** [comment]
Thanks I'm all good for now :-)
