### ISSUE TITLE
JMSSource Connector throwing Invalid Java object for schema type ARRAY: class scala.runtime.BoxedUnit

### ISSUE THREAD

**Issue by michaelandrepearce** [datamountaineer/stream-reactor#182]
We are trying to get running the JMSSource connector, the source queue in JMS contains jms BytesMessage on setting up the JMSSource connector, we get thrown the below error though.

org.apache.kafka.connect.errors.DataException: Invalid Java object for schema type ARRAY: class scala.runtime.BoxedUnit
	at org.apache.kafka.connect.data.ConnectSchema.validateValue(ConnectSchema.java:233)
	at org.apache.kafka.connect.data.Struct.put(Struct.java:215)
	at org.apache.kafka.connect.data.Struct.put(Struct.java:204)
	at com.datamountaineer.streamreactor.connect.jms.source.domain.JMSStructMessage$.getStruct(JMSStructMessage.scala:75)
	at com.datamountaineer.streamreactor.connect.jms.source.readers.JMSReader.convert(JMSReader.scala:59)
	at com.datamountaineer.streamreactor.connect.jms.source.readers.JMSReader$$anonfun$3$$anonfun$apply$2.apply(JMSReader.scala:50)
	at com.datamountaineer.streamreactor.connect.jms.source.readers.JMSReader$$anonfun$3$$anonfun$apply$2.apply(JMSReader.scala:50)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.datamountaineer.streamreactor.connect.jms.source.readers.JMSReader$$anonfun$3.apply(JMSReader.scala:50)
	at com.datamountaineer.streamreactor.connect.jms.source.readers.JMSReader$$anonfun$3.apply(JMSReader.scala:47)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at com.datamountaineer.streamreactor.connect.jms.source.readers.JMSReader.poll(JMSReader.scala:47)
	at com.datamountaineer.streamreactor.connect.jms.source.JMSSourceTask.poll(JMSSourceTask.scala:55)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:155)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2017-05-16 12:07:07,126] ERROR Task is being killed and

**Comment by andrewstevenson** [comment]
Thanks for the bug report, we’ll get on it.

FYI Pull requests welcome if you fancy having ago yourself!

**Comment by michaelandrepearce** [comment]
The issue is what is being set for properties is completely the wrong type, its meant to be an array of of struct , can't simply pass a map.

I've raise a basic fix for this here:
https://github.com/datamountaineer/stream-reactor/pull/183

Though surprised this works at all for anyone.

**Comment by stheppi** [comment]
Indeed it wasn't. We were returning Unit not even the map. Thanks again for the PR
