### ISSUE TITLE
Avro "bytes" type is not properly cast and can't be used.

### ISSUE THREAD

**Issue by eKIK** [datamountaineer/stream-reactor#204]
The "bytes" or "fixed" Avro type doesn't work with stream-reactor.

It's reproducible by setting up a schema + connector according to the description below and then sending some byte data, e.g. {"data": "\x01\x02\x03"} to the topic test-topic.

**Example Avro schema**
{
  "type": "record",
  "name": "test",
  "fields": [
    {
      "name": "data",
      "type": "bytes"
    }
  ]
}

**Example connector config**
name=test-sink
connector.class=com.datamountaineer.streamreactor.connect.hbase.HbaseSinkConnector
tasks.max=1
topics=test-topic
connect.hbase.sink.column.family=d
connect.hbase.sink.kcql=INSERT INTO test SELECT data FROM test-topic

**Error message in connectDistributed.out**
[2017-05-25 12:07:42,637] ERROR Task hbase-traffic-logs-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask:449
)                                                                              
java.lang.ClassCastException: java.nio.HeapByteBuffer cannot be cast to [B        
		at com.datamountaineer.streamreactor.connect.hbase.BytesHelper$ToBytesConverter$.fromBytes$extension(BytesHelper.scala)
		at com.datamountaineer.streamreactor.connect.hbase.StructFieldsExtractorBytes$$anonfun$com$datamountaineer$streamreactor$connect$hbase$StructFieldsExtrac
torBytes$$getFieldBytes$1.apply(StructFieldsExtractorBytes.scala:65)                      
		at com.datamountaineer.streamreactor.connect.hbase.StructFieldsExtractorBytes$$anonfun$com$datamountaineer$streamreactor$connect$hbase$StructFieldsExtrac
torBytes$$getFieldBytes$1.apply(StructFieldsExtractorBytes.scala:59)                                                                                
		at scala.Option.map(Option.scala:146)                                                                         
		at com.datamountaineer.streamreactor.connect.hbase.StructFieldsExtractorBytes.com$datamountaineer$streamreactor$connect$hbase$StructFieldsExtractorBytes$
$getFieldBytes(StructFieldsExtractorBytes.scala:59)
		at com.datamountaineer.streamreactor.connect.hbase.StructFieldsExtractorBytes$$anonfun$3.apply(StructFieldsExtractorBytes.scala:52)
		at com.datamountaineer.streamreactor.connect.hbase.StructFieldsExtractorBytes$$anonfun$3.apply(StructFieldsExtractorBytes.scala:51)                              at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
		at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)                                                               
		at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
		at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
		at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)                                                                                     at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
		at com.datamountaineer.streamreactor.connect.hbase.StructFieldsExtractorBytes.get(StructFieldsExtractorBytes.scala:51)                                
		at com.datamountaineer.streamreactor.connect.hbase.writers.HbaseWriter$$anonfun$insert$1$$anonfun$5.apply(HbaseWriter.scala:85)
		at com.datamountaineer.streamreactor.connect.hbase.writers.HbaseWriter$$anonfun$insert$1$$anonfun$5.apply(HbaseWriter.scala:78)
		at scala.collection.immutable.Stream.flatMap(Stream.scala:489)
		at com.datamountaineer.streamreactor.connect.hbase.writers.HbaseWriter$$anonfun$insert$1.apply(HbaseWriter.scala:78)
		at com.datamountaineer.streamreactor.connect.hbase.writers.HbaseWriter$$anonfun$insert$1.apply(HbaseWriter.scala:75)
		at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
		at com.datamountaineer.streamreactor.connect.hbase.writers.HbaseWriter.insert(HbaseWriter.scala:75)                                              
		at com.datamountaineer.streamreactor.connect.hbase.writers.HbaseWriter.write(HbaseWriter.scala:64)                                                               at com.datamountaineer.streamreactor.connect.hbase.HbaseSinkTask$$anonfun$put$2.apply(HbaseSinkTask.scala:89)
		at com.datamountaineer.streamreactor.connect.hbase.HbaseSinkTask$$anonfun$put$2.apply(HbaseSinkTask.scala:89)
		at scala.Option.foreach(Option.scala:257)
		at com.datamountaineer.streamreactor.connect.hbase.HbaseSinkTask.put(HbaseSinkTask.scala:89)
		at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:429)
		at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:250)
		at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:179)
		at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
		at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
		at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at java.lang.Thread.run(Thread.java:745)

**Comment by stheppi** [comment]
Latest commit has fixed the problem.
