### ISSUE TITLE
java.lang.NoSuchMethodError when tried kafka-connect-kudu

### ISSUE THREAD

**Issue by ChenShuai1981** [datamountaineer/stream-reactor#221]
I tried quick start example of kafka-connect-kudu on http://docs.datamountaineer.com/en/latest/kudu.html with latest confluent platform 3.2.2 and kudu 1.4.0 (running as quickstart vm on my mac), followed the guideline but met errors when I produce a sample message in kafka topic. Anyone can help?

kudu-sink.properties:

name=kudu-sink
connector.class=com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkConnector
tasks.max=1
connect.kudu.master=quickstart.cloudera
connect.kudu.sink.kcql = INSERT INTO kudu_test SELECT * FROM kudu_test AUTOCREATE DISTRIBUTEBY ID INTO 4 BUCKETS
topics=kudu_test

Stacktrace:

[2017-06-26 11:15:06,332] INFO Found schema for kudu_test-value (com.datamountaineer.streamreactor.connect.schemas.SchemaRegistry$:43)
[2017-06-26 11:15:06,332] INFO  (com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$:154)
[2017-06-26 11:15:06,340] ERROR Task kudu-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
java.lang.NoSuchMethodError: org.apache.avro.Schema$Field.defaultVal()Ljava/lang/Object;
	at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$$anonfun$7.apply(DbHandler.scala:170)
	at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$$anonfun$7.apply(DbHandler.scala:166)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$.getKuduCols(DbHandler.scala:166)
	at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$.getKuduSchema(DbHandler.scala:142)
	at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$.createTableProps(DbHandler.scala:120)
	at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$$anonfun$createTables$1$$anonfun$apply$3.apply(DbHandler.scala:89)
	at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$$anonfun$createTables$1$$anonfun$apply$3.apply(DbHandler.scala:89)
	at scala.collection.immutable.List.map(List.scala:273)
	at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$$anonfun$createTables$1.apply(DbHandler.scala:89)
	at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$$anonfun$createTables$1.apply(DbHandler.scala:85)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.Set$Set3.foreach(Set.scala:163)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$.createTables(DbHandler.scala:85)
	at com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter$$anonfun$3.apply(KuduWriter.scala:52)
	at com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter$$anonfun$3.apply(KuduWriter.scala:52)
	at scala.util.Try$.apply(Try.scala:192)
	at com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter.<init>(KuduWriter.scala:52)
	at com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter$.apply(KuduWriter.scala:43)
	at com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkTask.start(KuduSinkTask.scala:69)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:207)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by stheppi** [comment]
Hi,
  I guess connect loads an older version of org.apache.avro:avro jar. Can you make sure 1.8.1 is first on the class path when connect distributed starts?

**Comment by andrewstevenson** [comment]
it's for 3.2.2, have they bumped the avro version?

**Comment by ChenShuai1981** [comment]
Hi,
I can NOT find avro 1.8.1 jar on the classpath, but this one /confluent-3.2.2/share/java/schema-registry/avro-1.7.7.jar

**Comment by andrewstevenson** [comment]
We haven't upgraded to 3.2.2 yet please try 3.2.1

**Comment by stheppi** [comment]
You need to set the sink jar as first one in the classpath. What happens, the connect distributed is loading the 1.7.7 version and therefore it will throw the exception since that method doesn't exist on the Field.

**Comment by ChenShuai1981** [comment]
Noticed that kafka-connect-kudu-0.2.5-3.2.2-all.jar released, but after I tried with confluent 3.2.2, the same error happened, could you help have a look? 

The CLASSPATH print in connect distributed shows here: /Users/chenshuai1/dev/stream-reactor-0.2.5-3.2.2/bin/../libs/kafka-connect-azure-documentdb-0.2.5-3.2.2-all.jar:/Users/chenshuai1/dev/stream-reactor-0.2.5-3.2.2/bin/../libs/kafka-connect-blockchain-0.2.5-3.2.2-all.jar:/Users/chenshuai1/dev/stream-reactor-0.2.5-3.2.2/bin/../libs/kafka-connect-bloomberg-0.2.5-3.2.2-all.jar:/Users/chenshuai1/dev/stream-reactor-0.2.5-3.2.2/bin/../libs/kafka-connect-cassandra-0.2.5-3.2.2-all.jar:/Users/chenshuai1/dev/stream-reactor-0.2.5-3.2.2/bin/../libs/kafka-connect-coap-0.2.5-3.2.2-all.jar:/Users/chenshuai1/dev/stream-reactor-0.2.5-3.2.2/bin/../libs/kafka-connect-druid-0.2.5-3.2.2-all.jar:/Users/chenshuai1/dev/stream-reactor-0.2.5-3.2.2/bin/../libs/kafka-connect-elastic-0.2.5-3.2.2-all.jar:/Users/chenshuai1/dev/stream-reactor-0.2.5-3.2.2/bin/../libs/kafka-connect-ftp-0.2.5-3.2.2-all.jar:/Users/chenshuai1/dev/stream-reactor-0.2.5-3.2.2/bin/../libs/kafka-connect-hazelcast-0.2.5-3.2.2-all.jar:/Users/chenshuai1/dev/stream-reactor-0.2.5-3.2.2/bin/../libs/kafka-connect-hbase-0.2.5-3.2.2-all.jar:/Users/chenshuai1/dev/stream-reactor-0.2.5-3.2.2/bin/../libs/kafka-connect-influxdb-0.2.5-3.2.2-all.jar:/Users/chenshuai1/dev/stream-reactor-0.2.5-3.2.2/bin/../libs/kafka-connect-jms-0.2.5-3.2.2-all.jar:/Users/chenshuai1/dev/stream-reactor-0.2.5-3.2.2/bin/../libs/kafka-connect-kudu-0.2.5-3.2.2-all.jar:/Users/chenshuai1/dev/stream-reactor-0.2.5-3.2.2/bin/../libs/kafka-connect-mongodb-0.2.5-3.2.2-all.jar:/Users/chenshuai1/dev/stream-reactor-0.2.5-3.2.2/bin/../libs/kafka-connect-mqtt-0.2.5-3.2.2-all.jar:/Users/chenshuai1/dev/stream-reactor-0.2.5-3.2.2/bin/../libs/kafka-connect-redis-0.2.5-3.2.2-all.jar:/Users/chenshuai1/dev/stream-reactor-0.2.5-3.2.2/bin/../libs/kafka-connect-rethink-0.2.5-3.2.2-all.jar:/Users/chenshuai1/dev/stream-reactor-0.2.5-3.2.2/bin/../libs/kafka-connect-voltdb-0.2.5-3.2.2-all.jar:/Users/chenshuai1/dev/stream-reactor-0.2.5-3.2.2/bin/../libs/kafka-connect-yahoo-0.2.5-3.2.2-all.jar:/Users/chenshuai1/dev/confluent-3.2.2/share/java/confluent-common/*:/Users/chenshuai1/dev/confluent-3.2.2/share/java/kafka-serde-tools/*:/Users/chenshuai1/dev/confluent-3.2.2/share/java/kafka-connect-elasticsearch/*:/Users/chenshuai1/dev/confluent-3.2.2/share/java/kafka-connect-hdfs/*:/Users/chenshuai1/dev/confluent-3.2.2/share/java/kafka-connect-jdbc/*:/Users/chenshuai1/dev/confluent-3.2.2/share/java/kafka-connect-kudu/*:/Users/chenshuai1/dev/confluent-3.2.2/share/java/kafka-connect-s3/*:/Users/chenshuai1/dev/confluent-3.2.2/share/java/kafka-connect-storage-common/*

**Comment by andrewstevenson** [comment]
Will be fixed in #231, Classpath issue resolvable by setting the classpath, Confluent 3.3 upgrades to Avro 1.8.2
