### ISSUE TITLE
Redis Sink error - class java.util.HashMap is not valid. Expecting a Struct

### ISSUE THREAD

**Issue by Crystark** [datamountaineer/stream-reactor#237]
Hi,

I'm referencing https://github.com/datamountaineer/stream-reactor/issues/137 because it kinda seems like the same problem.

We're trying to use the RedisSinkConnector with the following properties:

```
name=my-topic.redis-sink
connect.redis.connection.host=localhost
connect.redis.connection.port=6379
connector.class=com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkConnector
tasks.max=1
topics=my-topic
connect.redis.sink.kcql=INSERT INTO CMD- SELECT linkedId FROM my-topic PK id
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false
```

And are getting the following error:

```
[2017-08-03 10:14:33,293] ERROR Encountered error class java.util.HashMap is not valid. Expecting a Struct (com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache:62)
java.lang.RuntimeException: class java.util.HashMap is not valid. Expecting a Struct
        at scala.sys.package$.error(package.scala:27)
        at com.datamountaineer.streamreactor.connect.schemas.ConverterUtil$class.convert(ConverterUtil.scala:163)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisWriter.convert(RedisWriter.scala:29)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$4.apply(RedisCache.scala:74)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$4.apply(RedisCache.scala:69)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike$class.map(SetLike.scala:92)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RedisCache.scala:69)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RedisCache.scala:68)
        at scala.collection.immutable.Stream.foreach(Stream.scala:594)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1.apply$mcV$sp(RedisCache.scala:68)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1.apply(RedisCache.scala:68)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1.apply(RedisCache.scala:68)
        at scala.util.Try$.apply(Try.scala:192)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1.apply(RedisCache.scala:66)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1.apply(RedisCache.scala:60)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache.insert(RedisCache.scala:60)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache.write(RedisCache.scala:54)
        at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask$$anonfun$put$2.apply(RedisSinkTask.scala:106)
        at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask$$anonfun$put$2.apply(RedisSinkTask.scala:106)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask.put(RedisSinkTask.scala:106)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:429)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:250)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:179)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2017-08-03 10:14:33,294] ERROR Task my-topic.redis-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask:449)
java.lang.RuntimeException: java.lang.RuntimeException: class java.util.HashMap is not valid. Expecting a Struct
        at com.datamountaineer.streamreactor.connect.errors.ThrowErrorPolicy.handle(ErrorPolicy.scala:58)
        at com.datamountaineer.streamreactor.connect.errors.ErrorHandler$class.handleError(ErrorHandler.scala:83)
        at com.datamountaineer.streamreactor.connect.errors.ErrorHandler$class.handleTry(ErrorHandler.scala:64)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisWriter.handleTry(RedisWriter.scala:29)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1.apply(RedisCache.scala:81)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1.apply(RedisCache.scala:60)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache.insert(RedisCache.scala:60)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache.write(RedisCache.scala:54)
        at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask$$anonfun$put$2.apply(RedisSinkTask.scala:106)
        at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask$$anonfun$put$2.apply(RedisSinkTask.scala:106)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask.put(RedisSinkTask.scala:106)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:429)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:250)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:179)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: class java.util.HashMap is not valid. Expecting a Struct
        at scala.sys.package$.error(package.scala:27)
        at com.datamountaineer.streamreactor.connect.schemas.ConverterUtil$class.convert(ConverterUtil.scala:163)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisWriter.convert(RedisWriter.scala:29)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$4.apply(RedisCache.scala:74)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1$$anonfun$apply$mcV$sp$1$$anonfun$apply$4.apply(RedisCache.scala:69)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
        at scala.collection.SetLike$class.map(SetLike.scala:92)
        at scala.collection.AbstractSet.map(Set.scala:47)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RedisCache.scala:69)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(RedisCache.scala:68)
        at scala.collection.immutable.Stream.foreach(Stream.scala:594)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1.apply$mcV$sp(RedisCache.scala:68)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1.apply(RedisCache.scala:68)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1$$anonfun$1.apply(RedisCache.scala:68)
        at scala.util.Try$.apply(Try.scala:192)
        at com.datamountaineer.streamreactor.connect.redis.sink.writer.RedisCache$$anonfun$insert$1.apply(RedisCache.scala:66)
        ... 19 more
```

Are we missing anything here ? Is there anyway to fix this ?
Thanks

**Comment by andrewstevenson** [comment]
@Crystark How did you start the Connect cluster? Can you share the properties?

**Comment by Crystark** [comment]
Thanks for the quick answer.

We launched the connect cluster with the following command:
```
./stream-reactor-0.2.5-3.2.0/bin/start-connect.sh
```

We're not specifying a specific properties file but if you're talking about the default one (`connect-avro-distributed.properties`) here it is:

```
# Sample configuration for a distributed Kafka Connect worker that uses Avro serialization and
# integrates the the Schema Registry. This sample configuration assumes a local installation of
# Confluent Platform with all services running on their default ports.

# Bootstrap Kafka servers. If multiple servers are specified, they should be comma-separated.
bootstrap.servers=localhost:9092

# The group ID is a unique identifier for the set of workers that form a single Kafka Connect
# cluster
group.id=connect-cluster

# The converters specify the format of data in Kafka and how to translate it into Connect data.
# Every Connect user will need to configure these based on the format they want their data in
# when loaded from or stored into Kafka
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://localhost:8081
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://localhost:8081

# The internal converter used for offsets and config data is configurable and must be specified,
# but most users will always want to use the built-in default. Offset and config data is never
# visible outside of Connect in this format.
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false

# Kafka topic where connector configuration will be persisted. You should create this topic with a
# single partition and high replication factor (e.g. 3)
config.storage.topic=connect-configs

# Kafka topic where connector offset data will be persisted. You should create this topic with many
# partitions (e.g. 25) and high replication factor (e.g. 3)
offset.storage.topic=connect-offsets

# Kafka topic where connector status data will be persisted. You should create this topic with many
# partitions (e.g. 25) and high replication factor (e.g. 3)
status.storage.topic=connect-statuses

# Confuent Control Center Integration -- uncomment these lines to enable Kafka client interceptors
# that will report audit data that can be displayed and analyzed in Confluent Control Center
# producer.interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
# consumer.interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
```

Then there's our connector override properties that I gave you in the first message.

**Comment by stheppi** [comment]
@Crystark 
 the issue if we can call it an issue is the Redis sink unlike the Cassandra/Rethink/InfluxDb doesn't handle non avro records for now.
 if you have  avro payloads all you have to do is remove `value.converter=org.apache.kafka.connect.json.JsonConverter` otherwise you need wait until we add support for json string or json bytes being sent in the kafka message

**Comment by andrewstevenson** [comment]
@Crystark It's on our roadmap. If it's really urgent you can sponsor the fix. We recommend using Avro payloads with Schema Registry integration.

**Comment by Crystark** [comment]
Any ETA on that ?

Just to give you the big picture, we wanted to use the redis connector to insert data into Apache Geode using it's own Redis Adapter as a way to gain a bit of time. We could put avro in our topics but this is going slightly too far as this was supposed to be a temporary solution until we make our own GeodeSinkConnector. We'll probably be doing a simple Kafka Stream that writes our data into Geode first until we can tackle the learning curve of creating a kafka connector using your kcql.

I'm going a bit off topic but any chance you may be doing a GeodeSinkConnector in the future ? Your kcql inserts could mirror geode's oql querys. You're talking about sponsorship, how does this work ? I'd be interested in knowing the details.

Thanks

**Comment by andrewstevenson** [comment]
@Crystark I'm closing this as it's not support yet and we have a direct mail conversation in progress.
