### ISSUE TITLE
Kafka Connect Cassandra Sink

### ISSUE THREAD

**Issue by eman23** [datamountaineer/stream-reactor#244]
I tried to connect kafka with cassandra locally and it worked fine. But I have a problem when another machine tries to connect with me and send data it appears an error with serialization and deserialization **at datamountaineer cassandra sink shell as follow:**
```
 ERROR Task cassandra-sink-orders-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:141)
org.apache.kafka.connect.errors.DataException: orders-topic
	at io.confluent.connect.avro.AvroConverter.toConnectData(AvroConverter.java:92)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:401)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:249)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:179)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at `java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)`
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id -1
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!

```
**and these errors at kafka sink:**
```
ERROR Unknown error when running consumer:  (kafka.tools.ConsoleConsumer$:105)
org.apache.kafka.common.errors.SerializationException: Error retrieving Avro schema for id 61
Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema not found; error code: 40403
	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:170)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:188)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getId(RestService.java:330)
	at io.confluent.kafka.schemaregistry.client.rest.RestService.getId(RestService.java:323)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getSchemaByIdFromRegistry(CachedSchemaRegistryClient.java:63)
	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getBySubjectAndID(CachedSchemaRegistryClient.java:118)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:121)
	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:92)
	at io.confluent.kafka.formatter.AvroMessageFormatter.writeTo(AvroMessageFormatter.java:120)
	at io.confluent.kafka.formatter.AvroMessageFormatter.writeTo(AvroMessageFormatter.java:112)
	at kafka.tools.ConsoleConsumer$.process(ConsoleConsumer.scala:137)
	at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:75)
	at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:50)
	at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)

```
**and that in another trials:**

```
ERROR Unknown error when running consumer:  (kafka.tools.ConsoleConsumer$:105)
org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id -1
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!
```
 
I have tried for more than 5 hours and nothing change 
could you help me to solve this issue!!

**Comment by stheppi** [comment]
The other machine is using a different instance of schema registry. So you sink running on your machine uses it's own schema registry instance thus the ids between those two won't match.

**Comment by eman23** [comment]
what is the meaning of the ids between those machines 
and how can I manage it ?

**Comment by andrewstevenson** [comment]
you can't, they are assigned by the schema registry and are the pointers to the id of the schema for the serializers to convert with. Check out the Confluents docs.

**Comment by stheppi** [comment]
@eman23 
Guys, we have no problem to describe to you what and how Connect works but that is part of our training service.

Usually when I work with a technology I dont' know about i read the documentation first. 

Schema registry stores your avro schemas. Each entry is given an id which is added to the Kafka raw byte message. If you run the schema registry on two machines individually the ids won't be the same.     I advise you to first have a good read of this: http://docs.confluent.io/current/schema-registry/docs/intro.html

**Comment by stheppi** [comment]
Also `Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!` 
You have pushed non avro messages on the topic orders.

**Comment by stheppi** [comment]
You can join our slack channel and we can give more guidance on the setup. 
Your colleague connecting to your machine needs to use the same schema registry instance otherwise you end up in trouble with deserialization.
Also, make sure you push avro to the topic
