### ISSUE TITLE
Elastic5 connector fails to start up

### ISSUE THREAD

**Issue by heliocentrist** [datamountaineer/stream-reactor#269]
Hello! I have a problem deploying the elastic 5 connector to Kubernetes. It looks like the Kafka Connect service fails to start up. Here are the last lines of the pod log:

```
===> Launching kafka-connect ...
Waiting for connect's rest API at http://10.244.3.161:9102
2017-09-06 14:22:44.075:INFO:ipjsoejs.Server:jetty-8.y.z-SNAPSHOT
2017-09-06 14:22:44.176:INFO:ipjsoejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:9102
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/etc/datamountaineer/jars/kafka-connect-elastic5-0.3.0-3.3.0-all.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/kafka/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/kafka-connect-hdfs/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Waiting for connect's rest API at http://10.244.3.161:9102
Waiting for connect's rest API at http://10.244.3.161:9102
Waiting for connect's rest API at http://10.244.3.161:9102
Waiting for connect's rest API at http://10.244.3.161:9102
Waiting for connect's rest API at http://10.244.3.161:9102
Waiting for connect's rest API at http://10.244.3.161:9102
Waiting for connect's rest API at http://10.244.3.161:9102
Waiting for connect's rest API at http://10.244.3.161:9102
Waiting for connect's rest API at http://10.244.3.161:9102
Waiting for connect's rest API at http://10.244.3.161:9102
Waiting for connect's rest API at http://10.244.3.161:9102
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.collect.Sets$SetView.iterator()Lcom/google/common/collect/UnmodifiableIterator;
	at org.reflections.Reflections.expandSuperTypes(Reflections.java:380)
	at org.reflections.Reflections.<init>(Reflections.java:126)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanPluginPath(DelegatingClassLoader.java:221)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.scanUrlsAndAddPlugins(DelegatingClassLoader.java:198)
	at org.apache.kafka.connect.runtime.isolation.DelegatingClassLoader.initLoaders(DelegatingClassLoader.java:159)
	at org.apache.kafka.connect.runtime.isolation.Plugins.<init>(Plugins.java:47)
	at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:63)
```

I would appreciate any help in investigating the problem :) If it helps, I can show the full pod log.

**Comment by andrewstevenson** [comment]
Which docker image?

**Comment by heliocentrist** [comment]
registry.hub.docker.com/datamountaineer/kafka-connect-elastic5:0.3.0

**Comment by andrewstevenson** [comment]
can you check the contents of ``/etc/kafka-connect/kafka-connect.properties``. it should have `plugin.path` which points to `/etc/datamountaineer/jars` this gives classloader isolation.

**Comment by heliocentrist** [comment]
These are all the env variables that start with `CONNECT_`:

```
CONNECT_BOOTSTRAP_SERVERS=kafka:9092
CONNECT_CONFIG_STORAGE_TOPIC=connect_my-elastic_configs
CONNECT_ELASTIC_BATCH_SIZE=4000
CONNECT_ELASTIC_CLUSTER_NAME=my-elastic
CONNECT_ELASTIC_ERROR_POLICY=THROW
CONNECT_ELASTIC_KCQL=<...>
CONNECT_ELASTIC_MAX_RETRIES=20
CONNECT_ELASTIC_URL=elastic:9200
CONNECT_ELASTIC_URL_PREFIX=elasticsearch
CONNECT_ELASTIC_USE_HTTP=tcp
CONNECT_ELASTIC_WRITE_TIMEOUT=300000
CONNECT_ELASTIC_XPACK_PLUGINS=
CONNECT_ELASTIC_XPACK_SETTINGS=<...>
CONNECT_GROUP_ID=my-elastic
CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=
CONNECT_LOG4J_ROOT_LOGLEVEL=
CONNECT_OFFSET_STORAGE_TOPIC=connect_my-elastic_offsets
CONNECT_PLUGIN_PATH=/etc/datamountaineer/jars
CONNECT_PROGRESS_ENABLED=false
CONNECT_REST_ADVERTISED_HOST_NAME=10.244.4.22
CONNECT_REST_PORT=9102
CONNECT_STATUS_STORAGE_TOPIC=connect_my-elastic_statuses
CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=
```

I'll see if I can access the file you mentioned inside the pod.

**Comment by andrewstevenson** [comment]
It look like it's getting loaded in the classpath rather than the plugin.path

I've pushed a fix.

**Comment by heliocentrist** [comment]
Thanks @andrewstevenson , I'll try it and report back.

**Comment by andrewstevenson** [comment]
It's building and pushing now.

**Comment by heliocentrist** [comment]
@andrewstevenson It looks like `datamountaineer/kafka-connect-elastic5` image wasn't updated, but `datamountaineer/kafka-connect-elastic` was.

**Comment by andrewstevenson** [comment]
@heliocentrist Our docker CI/CD was as smooth as yours ;-) Its there now https://hub.docker.com/r/datamountaineer/kafka-connect-elastic5/tags/

**Comment by andrewstevenson** [comment]
@heliocentrist Did you have succes?

**Comment by andrewstevenson** [comment]
@heliocentrist Can I close this issue?

**Comment by heliocentrist** [comment]
@andrewstevenson Sorry for not answering before! I was off for a few days. I'm working on this task right now, and will give you an update before midday today.

**Comment by heliocentrist** [comment]
@andrewstevenson I can confirm that with the new image the issue is fixed for us. Thanks a lot for your help!

**Comment by andrewstevenson** [comment]
👍 No problem, anything else let us know.
