### ISSUE TITLE
Kudu Sink Connector - Table not found

### ISSUE THREAD

**Issue by tapvirvirk** [datamountaineer/stream-reactor#271]
Hi,

I am integrating Kafka Kudu Sink Connector and getting below error message.  My Kudu is installed on Hadoop Cluster which is Kerberose Authenticated.

Below issue is occurring when I'm changing the value.converter & key.converter to AvroConvertor.

Caused by: org.apache.kafka.connect.errors.ConnectException: The following tables are not found and not set for autocreate com.datamountaineer.kcql.Kcql@1eea6ad2
        at com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$.buildTableCache(DbHandler.scala:67)
        at com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter.com$datamountaineer$streamreactor$connect$kudu$sink$KuduWriter$$kuduTablesCache$lzycompute(KuduWriter.scala:61)
  

However, if I use jsonConvertor, getting a different error "DataException: Converting byte[] to Kafka Connect data failed due to serialization error" Further it is saying "Invalid UTF8 Character"
Caused by: java.io.CharConversionException: Invalid UTF-32 character 0x1cc0a06(above 10ffff)  at char #1, byte #7)
        at com.fasterxml.jackson.core.io.UTF32Reader.reportInvalid(UTF32Reader.java:189)
        at com.fasterxml.jackson.core.io.UTF32Reader.read(UTF32Reader.java:150)
        at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._loadMore(ReaderBasedJsonParser.java:241)

Can you please help in the issue? If i'm using wrong configuration or something else?

Thanks
Tapvir

**Comment by andrewstevenson** [comment]
@tapvirvirk What's your connector configuration?  Do the tables existing in Kudu as the log messages states "The following tables are not found and not set for autocreate"

**Comment by andrewstevenson** [comment]
@tapvirvirk Also what version of the connector are you using?

**Comment by tapvirvirk** [comment]
@andrewstevenson Its 0.3.0 and confluent is 3.3.0 and java is 1.8 and scala is 2.11.8

**Comment by andrewstevenson** [comment]
and your config?

**Comment by tapvirvirk** [comment]
@andrewstevenson yes
Query submitted at: 2017-09-08 19:04:08 (Coordinator: http://xxxxx:25000)
Query progress can be monitored at: http://xxxxx:25000/query_plan?query_id=5b4c77615818a954:f2fe906900000000
+----------+
| count(1) |
+----------+
| 0        |
+----------+
Fetched 1 row(s) in 1.56s


[2017-09-08 19:22:03,708] INFO     ____        __        __  ___                  __        _
   / __ \____ _/ /_____ _/  |/  /___  __  ______  / /_____ _(_)___  ___  ___  _____
  / / / / __ `/ __/ __ `/ /|_/ / __ \/ / / / __ \/ __/ __ `/ / __ \/ _ \/ _ \/ ___/
 / /_/ / /_/ / /_/ /_/ / /  / / /_/ / /_/ / / / / /_/ /_/ / / / / /  __/  __/ /
/_____/\__,_/\__/\__,_/_/  /_/\____/\__,_/_/ /_/\__/\__,_/_/_/ /_/\___/\___/_/
       __ __          __      _____ _       __
      / //_/_  ______/ /_  __/ ___/(_)___  / /__
     / ,< / / / / __  / / / /\__ \/ / __ \/ //_/
    / /| / /_/ / /_/ / /_/ /___/ / / / / / ,<
   /_/ |_\__,_/\__,_/\__,_//____/_/_/ /_/_/|_| by Andrew Stevenson

 v  (com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkTask:44)
[2017-09-08 19:22:03,712] INFO KuduConfig values:
        connect.kudu.error.policy = THROW
        connect.kudu.kcql = INSERT INTO kudu_test SELECT * FROM kudu-table-topic
        connect.kudu.master = amz-devteam-analytics-cdh02.pointclickcare.com
        connect.kudu.max.retries = 10
        connect.kudu.mutation.buffer.space = 1000
        connect.kudu.retry.interval = 60000
        connect.kudu.schema.registry.url = http://localhost:8081
        connect.kudu.write.flush.mode = SYNC
        connect.progress.enabled = true
 (com.datamountaineer.streamreactor.connect.kudu.config.KuduConfig:223)
[2017-09-08 19:22:03,816] INFO Finished creating connector kuduTapvirTest (org.apache.kafka.connect.runtime.Worker:225)
[2017-09-08 19:22:03,818] INFO SinkConnectorConfig values:
        connector.class = com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkConnector
        key.converter = null
        name = kuduTapvirTest
        tasks.max = 1
        topics = [kudu-table-topic]
        transforms = null
        value.converter = null
 (org.apache.kafka.connect.runtime.SinkConnectorConfig:223)
[2017-09-08 19:22:03,818] INFO EnrichedConnectorConfig values:
        connector.class = com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkConnector
        key.converter = null
        name = kuduTapvirTest
        tasks.max = 1
        topics = [kudu-table-topic]
        transforms = null
        value.converter = null
 (org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig:223)

**Comment by tapvirvirk** [comment]
@andrewstevenson 
kafka-avro-console-producer  --broker-list localhost:9092 --topic kudu-table-topic --property value.schema='{"type":"record","name":"myrecord","fields":[{"name":"id","type":"int"},
{"name":"random_field", "type": "string"}]}'
{"id": 678, "random_field": "foo"}

**Comment by andrewstevenson** [comment]
Have you created `kudu_test ` in Kudu?

**Comment by tapvirvirk** [comment]
yes

**Comment by tapvirvirk** [comment]
Like I mentioned, Kudu is installed on Hadoop Cluster. And Cluster has kerberose authenticated

**Comment by tapvirvirk** [comment]
Will this be related to this error?

**Comment by andrewstevenson** [comment]
is Kudu kerberoised?

**Comment by tapvirvirk** [comment]
yes

**Comment by tapvirvirk** [comment]
Sorry, I just checked. It is not

**Comment by tapvirvirk** [comment]
Kudu version 1.3

**Comment by tapvirvirk** [comment]
How to make "Sink in auto create mode"

**Comment by andrewstevenson** [comment]
can you run with AUTOCREATE kcql?

**Comment by andrewstevenson** [comment]
http://docs.datamountaineer.com/en/latest/kudu.html

**Comment by andrewstevenson** [comment]
are you on a docker?

**Comment by tapvirvirk** [comment]
No. After runing kcql in AUTCREATE, getting below error
Caused by: org.apache.kafka.connect.errors.ConnectException: DISTRIBUTEBY columns INTO BUCKETS n must be specified for table auto creation!

**Comment by tapvirvirk** [comment]
How to specify DISTRIBYTEDBY in kcql?

**Comment by tapvirvirk** [comment]
Current query: INSERT INTO kudu_test SELECT * FROM kudu-table-topic AUTOCREATE

**Comment by andrewstevenson** [comment]
https://github.com/datamountaineer/stream-reactor/blob/master/kafka-connect-kudu/src/test/scala/com/datamountaineer/streamreactor/connect/kudu/TestBase.scala#L42

In the docs 

#Insert mode, select all fields from topicA and write to tableA
INSERT INTO tableA SELECT * FROM topicA

#Insert mode, select 3 fields and rename from topicB and write to tableB
INSERT INTO tableB SELECT x AS a, y AS b and z AS c FROM topicB

#Upsert mode, select all fields from topicC, auto create tableC and auto evolve, use field1 and field2 as the primary keys
UPSERT INTO tableC SELECT * FROM topicC AUTOCREATE  DISTRIBUTEBY field1, field2 INTO 10 BUCKETS AUTOEVOLVE

**Comment by tapvirvirk** [comment]
Thanks Andrew.
 v  (com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkTask:44)
[2017-09-08 20:05:35,875] INFO KuduConfig values:
        connect.kudu.error.policy = THROW
        connect.kudu.kcql = UPSERT INTO kudu_test SELECT * FROM kudu-table-topic AUTOCREATE DISTRIBUTEBY id,random_field  INTO 10 BUCKETS AUTOEVOLV
        connect.kudu.master = amz-devteam-analytics-cdh02.pointclickcare.com:7051
        connect.kudu.max.retries = 20
        connect.kudu.mutation.buffer.space = 1000
        connect.kudu.retry.interval = 60000
        connect.kudu.schema.registry.url = http://localhost:8081
        connect.kudu.write.flush.mode = SYNC
        connect.progress.enabled = true
 (com.datamountaineer.streamreactor.connect.kudu.config.KuduConfig:223)


[2017-09-08 20:05:41,134] WARN Unable to create tables at startup! Tables will be created on delivery of the first record (com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter:58)
org.apache.kudu.client.NonRecoverableException: Table kudu-table-topic already exists with id b4fbd9373c464f99b0a48b422ca9ee91
        at org.apache.kudu.client.TabletClient.dispatchMasterErrorOrReturnException(TabletClient.java:557)
        at org.apache.kudu.client.TabletClient.messageReceived(TabletClient.java:467)
        at org.apache.kudu.client.shaded.org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.apache.kudu.client.TabletClient.handleUpstream(TabletClient.java:603)
        at org.apache.kudu.client.shaded.org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.apache.kudu.client.shaded.org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.apache.kudu.client.shaded.org.jboss.netty.handler.timeout.ReadTimeoutHandler.messageReceived(ReadTimeoutHandler.java

**Comment by andrewstevenson** [comment]
Ok, that's a warning. I've push a fix on the logging to show which tables it can't find. you'll need to `gradle fatJar` in the kudu folder on the maste branch, this will build the latest jar and put it in the build/libs folder.

**Comment by tapvirvirk** [comment]
This is what I'm getting 
[2017-09-08 20:12:55,528] ERROR Encountered error Table kudu-test-2 already exists with id 4c4c7fa9a0754c10a76f209fc039b2b3 (com.datamountaineer.streamreactor.connect.kudu.sink.KuduWriter:62)
org.apache.kudu.client.NonRecoverableException: Table kudu-test-2 already exists with id 4c4c7fa9a0754c10a76f209fc039b2b3

**Comment by tapvirvirk** [comment]
I tried to change the topic name and getting the same error

**Comment by tapvirvirk** [comment]
Hi Andrew, I'm not much familiar with compiling the code. Can you compile only kudu jar and attach it in the ticket?

**Comment by andrewstevenson** [comment]
try this link to get the fix, I've seen one issue that's fixed with this one,hopefully https://github.com/datamountaineer/stream-reactor/releases/download/0.3.0.1-alpha/kafka-connect-kudu-0.3.0-3.3.0-all.jar

**Comment by tapvirvirk** [comment]
Thanks. 
Let me try and I will let you know.

Also should I use json convertor or avro convertor?

**Comment by andrewstevenson** [comment]
Avro.

**Comment by tapvirvirk** [comment]
Now, I'm not getting error. Her's the message
[2017-09-08 20:45:40,315] WARN Slow DNS lookup! Resolved IP of `amz-devteam-analytics-cdh06.pointclickcare.com' to amz-devteam-analytics-cdh06.pointclickcare.com/172.16.11.231 in 4445444ns (org.apache.kudu.util.NetUtil:106)
[2017-09-08 20:45:40,331] INFO Delivered 2 records for kudu-test-2 since 2017-09-08 20:42:56 (com.datamountaineer.streamreactor.connect.utils.ProgressCounter:43)

But not seeing the records in Kudu table

[amz-devteam-analytics-cdh06.pointclickcare.com:21000] > select * from kudu_test;
Query: select * from kudu_test
Query submitted at: 2017-09-08 20:46:31 (Coordinator: http://amz-devteam-analytics-cdh06.pointclickcare.com:25000)
Query progress can be monitored at: http://amz-devteam-analytics-cdh06.pointclickcare.com:25000/query_plan?query_id=f64661611e12f095:81d4c29000000000

Fetched 0 row(s) in 1.48s

**Comment by tapvirvirk** [comment]
[2017-09-08 20:48:55,525] INFO Delivered 3 records for kudu-test-2 since 2017-09-08 20:42:56 (com.datamountaineer.streamreactor.connect.utils.ProgressCounter:43)
[2017-09-08 20:48:56,548] INFO WorkerSinkTask{id=kuduTapvirTest-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:278)

**Comment by tapvirvirk** [comment]
Below is error coming when I start the kafka connect
v  (com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkTask:44)
[2017-09-08 21:03:30,970] INFO KuduConfig values:
        connect.kudu.error.policy = THROW
        connect.kudu.kcql = INSERT INTO kudu_test SELECT id,random_field FROM kudu-test-2
        connect.kudu.master = amz-devteam-analytics-cdh02.pointclickcare.com:7051
        connect.kudu.max.retries = 20
        connect.kudu.mutation.buffer.space = 1000
        connect.kudu.retry.interval = 60000
        connect.kudu.schema.registry.url = http://localhost:8081
        connect.kudu.write.flush.mode = SYNC
        connect.progress.enabled = true
 (com.datamountaineer.streamreactor.connect.kudu.config.KuduConfig:223)
[2017-09-08 21:03:31,066] ERROR Error while starting connector testKuduConnector (org.apache.kafka.connect.runtime.WorkerConnector:108)
org.apache.kafka.common.config.ConfigException: Mandatory `topics` configuration contains topics not set in connect.kudu.kcql: Set(mytesttopic)
        at com.datamountaineer.streamreactor.connect.config.Helpers$.checkInputTopics(Helpers.scala:107)
        at com.datamountaineer.streamreactor.connect.kudu.sink.KuduSinkConnector.start(KuduSinkConnector.scala:62)
        at org.apache.kafka.connect.runtime.WorkerConnector.doStart(WorkerConnector.java:100)
        at org.apache.kafka.connect.runtime.WorkerConnector.start(WorkerConnector.java:125)
        at org.apache.kafka.connect.runtime.WorkerConnector.transitionTo(WorkerConnector.java:182)
        at org.apache.kafka.connect.runtime.Worker.startConnector(Worker.java:210)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.startConnector(DistributedHerder.java:872)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$1300(DistributedHerder.java:100)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:888)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$15.call(DistributedHerder.java:884)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by tapvirvirk** [comment]
But When I enter the avro records in producer below is the message coming

[2017-09-08 21:04:57,937] WARN Found missing tables  (com.datamountaineer.streamreactor.connect.kudu.sink.DbHandler$:61)
[2017-09-08 21:04:57,952] INFO Found schemas for kudu-test-2-value (com.datamountaineer.streamreactor.connect.schemas.SchemaRegistry$:71)
[2017-09-08 21:04:57,953] INFO Found schemas for kudu-test-value (com.datamountaineer.streamreactor.connect.schemas.SchemaRegistry$:71)
[2017-09-08 21:04:57,953] INFO Found schemas for test-kudu-value (com.datamountaineer.streamreactor.connect.schemas.SchemaRegistry$:71)
[2017-09-08 21:04:57,953] INFO Found schemas for kudu-test-1-value (com.datamountaineer.streamreactor.connect.schemas.SchemaRegistry$:71)
[2017-09-08 21:04:57,953] INFO Found schemas for kudu-table-topic-value (com.datamountaineer.streamreactor.connect.schemas.SchemaRegistry$:71)
[2017-09-08 21:04:58,025] WARN Slow DNS lookup! Resolved IP of `amz-devteam-analytics-cdh06.pointclickcare.com' to amz-devteam-analytics-cdh06.pointclickcare.com/172.16.11.231 in 3525037ns (org.apache.kudu.util.NetUtil:106)
[2017-09-08 21:04:58,076] INFO Delivered 1 records for kudu-test-2 since 2017-09-08 21:03:30 (com.datamountaineer.streamreactor.connect.utils.ProgressCounter:43)
[2017-09-08 21:05:00,940] INFO WorkerSinkTask{id=kuduTapvirTest-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSinkTask:278)

**Comment by andrewstevenson** [comment]
So the sink is writing records for the target of kudu-test-2. Have you set pushed a config with kcql containing mytesttopic?

**Comment by andrewstevenson** [comment]
I would suggest removing all the existing sinks and posting a fresh correct config.

**Comment by tapvirvirk** [comment]
yes. Initially I pushed it.

**Comment by tapvirvirk** [comment]
why I'm not to see the records in KUDU in kudu_test table?

**Comment by tapvirvirk** [comment]
Issue is resolved. I'm able to see the data in Kudu table now.

I was not appending the impala::default infront of table.

Correct kcql is : UPSERT INTO **impala::default.**kudu_test2 SELECT * FROM kudu-test-3 AUTOCREATE DISTRIBUTEBY id  INTO 2 BUCKETS AUTOEVOLVE

**Comment by andrewstevenson** [comment]
@tapvirvirk glad to here. We'll update the docs as this is chsnged with 1.4
