### ISSUE TITLE
MqttSourceConnector failed to load converter.

### ISSUE THREAD

**Issue by taigua** [datamountaineer/stream-reactor#282]
Version: kafka-connect-mqtt-0.3.0-3.3.0-all.jar
Confluent Version: confluent-3.3.0

I added plugin.path in connect-avro-standalone.properties ,
```ini
plugin.path=/opt/confluent-3.3.0/share/java/kafka-connect-mqtt
access.control.allow.methods=GET,POST,PUT,OPTIONS
access.control.allow.origin=*
```

and put kafka-connect-mqtt-0.3.0-3.3.0-all.jar (just this) in /opt/confluent-3.3.0/share/java/kafka-connect-mqtt then add a connector after confluent start:
```ini
name=MqttSourceConnector
connector.class=com.datamountaineer.streamreactor.connect.mqtt.source.MqttSourceConnector
tasks.max=1
connect.mqtt.hosts=tcp://127.0.0.1:1883
connect.mqtt.service.quality=1
connect.mqtt.kcql=INSERT INTO mqtt_kafka_topic SELECT * FROM mqtt2kafka WITHCONVERTER=com.datamountaineer.streamreactor.connect.source.converters.JsonSimpleConverter
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
```

but it couldn't load the JsonSimpleConverter.class (MqttSourceSettings.scala:93):
```log 
ERROR Failed to reconfigure connector's tasks, retrying after backoff: (org.apache.kafka.connect.runtime.distributed.DistributedHerder:922)
org.apache.kafka.common.config.ConfigException: Invalid connect.mqtt.kcql. com.datamountaineer.streamreactor.connect.source.converters.JsonSimpleConverter can't be found for mqtt2kafka
        at com.datamountaineer.streamreactor.connect.mqtt.config.MqttSourceSettings$$anonfun$apply$1.apply(MqttSourceSettings.scala:91)
        at com.datamountaineer.streamreactor.connect.mqtt.config.MqttSourceSettings$$anonfun$apply$1.apply(MqttSourceSettings.scala:88)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at com.datamountaineer.streamreactor.connect.mqtt.config.MqttSourceSettings$.apply(MqttSourceSettings.scala:88)
        at com.datamountaineer.streamreactor.connect.mqtt.source.MqttSourceConnector.taskConfigs(MqttSourceConnector.scala:48)
        at org.apache.kafka.connect.runtime.Worker.connectorTaskConfigs(Worker.java:271)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnector(DistributedHerder.java:963)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnectorTasksWithRetry(DistributedHerder.java:914)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.access$900(DistributedHerder.java:100)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$17$1.call(DistributedHerder.java:927)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder$17$1.call(DistributedHerder.java:924)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:249)
        at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:199)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2017-09-23 15:25:47,145] ERROR Unexpected error during connector task reconfiguration:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder:933)
[2017-09-23 15:25:47,145] ERROR Task reconfiguration for MqttSourceConnector failed unexpectedly, this connector will not be properly reconfigured unless manually triggered. (org.apache.kafka.connect.runtime.distributed.DistributedHerder:934)
```

It's wired. May anyone help? 
Thanks a lot.

**Comment by andrewstevenson** [comment]
Yes. That's a bit odd. I'll take a look tonight

**Comment by andrewstevenson** [comment]
@taigua Your converter class is wrong it should be `com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter`

**Comment by taigua** [comment]
@andrewstevenson 
Oops... 
Thank you, Andrew.

I  followed the doc (http://docs.datamountaineer.com/en/latest/mqtt.html), It's misleading.

> com.datamountaineer.streamreactor.connect.source.converters.AvroConverter
com.datamountaineer.streamreactor.connect.source.converters.JsonSimpleConverter
com.datamountaineer.streamreactor.connect.source.converters.BytesConverter

May someone correct it?

**Comment by andrewstevenson** [comment]
Done! Thanks!
