### ISSUE TITLE
MQTT source connector doesnt work after changing to version stream-reactor-0.3.0-3.3.0

### ISSUE THREAD

**Issue by joanna-** [datamountaineer/stream-reactor#283]
Now I am using version stream-reactor-0.3.0-3.3.0 with confluent 3.3.0. and previously I was using stream-reactor-0.2.4-3.1.1 with corresponding confluent version. 

I am trying to push data from MQTT to Cassandra via Kafka Confluent platform using Stream Reactor connectors. 

My configs for both connectors are:

- Cassandra Sink:
```
        "connector.class": "com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkConnector",
        "connect.cassandra.key.space": "devices_data",
        "connect.cassandra.contact.points": [my_host],
        "topics": "temperature",
        "tasks.max": "1",
        "connect.cassandra.port": "9042",
        "connect.cassandra.kcql": "INSERT INTO temp SELECT * FROM temperature;",
        "name": "cassandra_sinktemperature",
```
- MQTT Source:
```
        "connector.class": "com.datamountaineer.streamreactor.connect.mqtt.source.MqttSourceConnector",
        "connect.mqtt.connection.timeout": "1000",
        "tasks.max": "1",
        "name": "mqtt-sourcetemperature",
        "connect.mqtt.converters": "/temp=com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter",
        "connect.mqtt.connection.clean": "true",
        "connect.mqtt.kcql": "INSERT INTO temperature SELECT * FROM /temp;",
        "connect.mqtt.service.quality": "0",
        "connect.mqtt.connection.keep.alive": "1000",
        "connect.mqtt.converter.throw.on.error": "true",
        "connect.mqtt.hosts": "tcp://[my_host]:1883"
```
I have properly configured database table and all services are communicating well. When I was using version 0.2.4-3.1.1 of stream reactor, this setup was working and data from mqtt was being saved to database. 

This is my connect-distributed.properties:

```
bootstrap.servers=[my_host]:9092
group.id=connect-cluster
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=[my_host]:8081
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=[my_host]:8081
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
config.storage.topic=connect-configs
config.storage.replication.factor=1
offset.storage.topic=connect-offsets
offset.storage.replication.factor=1
status.storage.topic=connect-statuses
status.storage.replication.factor=1
plugin.path=/stream-reactor/stream-reactor-0.3.0-3.3.0/libs
```

When I am running this connector tasks now I get the JsonParseError (stacktrace in the bottom of description). I have examined this issue, since my messages are for sure valid Json and were working previously. 

Example json message which fails to be converted:
`
{"time":1506424015588,"id":"xxxxxxxxx","temp":"26.3096"}`

So I checked the schema registry for schemas for subjects and the result is:
```
{
    "subject": "temperature-key",
    "version": 1,
    "id": 1,
    "schema": "{\"type\":\"record\",\"name\":\"MsgKey\",\"namespace\":\"com.datamountaineer.streamreactor.connect.converters\",\"fields\":[{\"name\":\"topic\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"string\"}],\"connect.name\":\"com.datamountaineer.streamreactor.connect.converters.MsgKey\"}"
}
{
    "subject": "temperature-value",
    "version": 1,
    "id": 2,
    "schema": "\"bytes\""
}
```

With schema registry version (0.2.4-3.1.1 ) this was:

```
{
    "subject": "temperature-key",
    "version": 1,
    "id": 1,
    "schema": "{\"type\":\"record\",\"name\":\"MsgKey\",\"namespace\":\"com.datamountaineer.streamreactor.connect.converters.source\",\"fields\":[{\"name\":\"topic\",\"type\":\"string\"},{\"name\":\"id\",\"type\":\"int\"}],\"connect.name\":\"com.datamountaineer.streamreactor.connect.converters.source.MsgKey\"}"
}
{
    "subject": "temperature-value",
    "version": 1,
    "id": 2,
    "schema": "{\"type\":\"record\",\"name\":\"_temp\",\"fields\":[{\"name\":\"time\",\"type\":\"long\"},{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"temp\",\"type\":\"string\"}],\"connect.name\":\"_temp\"}"
}
```
Subjects are created in schema registry by MQTT source connector so I assume that the error lies somewhere in this connector. I guess that schema for "temperature value" should not be "bytes" because then it cannot be converted by Cassandra Sink Connector.

I would be very grateful for help with this issue since I have run out of ideas.

The full stacktrace is:

```
[2017-09-26 10:06:55,606] INFO AvroDataConfig values:
        schemas.cache.config = 1
        enhanced.avro.schema.support = false
        connect.meta.data = true
 (io.confluent.connect.avro.AvroDataConfig:170)
[2017-09-26 10:06:56,226] ERROR There was an error inserting the records Invalid json. (com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter:173)
java.lang.IllegalArgumentException: Invalid json.
        at com.datamountaineer.streamreactor.connect.converters.Transform$.raiseException$1(Transform.scala:39)
        at com.datamountaineer.streamreactor.connect.converters.Transform$.apply(Transform.scala:58)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$4$$anonfun$apply$3$$anonfun$apply$1.apply$mcV$sp(CassandraJsonWriter.scala:145)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$4$$anonfun$apply$3$$anonfun$apply$1.apply(CassandraJsonWriter.scala:144)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$4$$anonfun$apply$3$$anonfun$apply$1.apply(CassandraJsonWriter.scala:144)
        at com.datamountaineer.streamreactor.connect.concurrent.ExecutorExtension$RunnableWrapper$$anon$1.run(ExecutorExtension.scala:30)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'v': was expecting ('true', 'false' or 'null')
 at [Source: [B@210fcc14; line: 1, column: 3]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3524)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2686)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:878)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:772)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3834)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2404)
        at com.datamountaineer.streamreactor.connect.converters.Transform$$anonfun$1.apply(Transform.scala:57)
        at com.datamountaineer.streamreactor.connect.converters.Transform$$anonfun$1.apply(Transform.scala:57)
        at scala.util.Try$.apply(Try.scala:192)
        at com.datamountaineer.streamreactor.connect.converters.Transform$.apply(Transform.scala:57)
        ... 7 more
[2017-09-26 10:06:56,229] ERROR Encountered error Invalid json. (com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter:62)
java.lang.IllegalArgumentException: Invalid json.
        at com.datamountaineer.streamreactor.connect.converters.Transform$.raiseException$1(Transform.scala:39)
        at com.datamountaineer.streamreactor.connect.converters.Transform$.apply(Transform.scala:58)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$4$$anonfun$apply$3$$anonfun$apply$1.apply$mcV$sp(CassandraJsonWriter.scala:145)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$4$$anonfun$apply$3$$anonfun$apply$1.apply(CassandraJsonWriter.scala:144)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$4$$anonfun$apply$3$$anonfun$apply$1.apply(CassandraJsonWriter.scala:144)
        at com.datamountaineer.streamreactor.connect.concurrent.ExecutorExtension$RunnableWrapper$$anon$1.run(ExecutorExtension.scala:30)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'v': was expecting ('true', 'false' or 'null')
 at [Source: [B@210fcc14; line: 1, column: 3]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3524)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2686)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:878)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:772)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3834)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2404)
        at com.datamountaineer.streamreactor.connect.converters.Transform$$anonfun$1.apply(Transform.scala:57)
        at com.datamountaineer.streamreactor.connect.converters.Transform$$anonfun$1.apply(Transform.scala:57)
        at scala.util.Try$.apply(Try.scala:192)
        at com.datamountaineer.streamreactor.connect.converters.Transform$.apply(Transform.scala:57)
        ... 7 more
[2017-09-26 10:06:56,229] ERROR Task cassandra_sinktemperature-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask:455)
java.lang.RuntimeException: java.lang.IllegalArgumentException: Invalid json.
        at com.datamountaineer.streamreactor.connect.errors.ThrowErrorPolicy.handle(ErrorPolicy.scala:58)
        at com.datamountaineer.streamreactor.connect.errors.ErrorHandler$class.handleError(ErrorHandler.scala:83)
        at com.datamountaineer.streamreactor.connect.errors.ErrorHandler$class.handleTry(ErrorHandler.scala:64)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.handleTry(CassandraJsonWriter.scala:44)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.insert(CassandraJsonWriter.scala:174)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter.write(CassandraJsonWriter.scala:122)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkTask$$anonfun$put$2.apply(CassandraSinkTask.scala:67)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkTask$$anonfun$put$2.apply(CassandraSinkTask.scala:67)
        at scala.Option.foreach(Option.scala:257)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkTask.put(CassandraSinkTask.scala:67)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:435)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:251)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:180)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Invalid json.
        at com.datamountaineer.streamreactor.connect.converters.Transform$.raiseException$1(Transform.scala:39)
        at com.datamountaineer.streamreactor.connect.converters.Transform$.apply(Transform.scala:58)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$4$$anonfun$apply$3$$anonfun$apply$1.apply$mcV$sp(CassandraJsonWriter.scala:145)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$4$$anonfun$apply$3$$anonfun$apply$1.apply(CassandraJsonWriter.scala:144)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$4$$anonfun$apply$3$$anonfun$apply$1.apply(CassandraJsonWriter.scala:144)
        at com.datamountaineer.streamreactor.connect.concurrent.ExecutorExtension$RunnableWrapper$$anon$1.run(ExecutorExtension.scala:30)
        ... 3 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'v': was expecting ('true', 'false' or 'null')
 at [Source: [B@210fcc14; line: 1, column: 3]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1702)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:558)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3524)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2686)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:878)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:772)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3834)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3783)
        at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:2404)
        at com.datamountaineer.streamreactor.connect.converters.Transform$$anonfun$1.apply(Transform.scala:57)
        at com.datamountaineer.streamreactor.connect.converters.Transform$$anonfun$1.apply(Transform.scala:57)
        at scala.util.Try$.apply(Try.scala:192)
        at com.datamountaineer.streamreactor.connect.converters.Transform$.apply(Transform.scala:57)
        ... 7 more
[2017-09-26 10:06:56,230] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerSinkTask:456)
[2017-09-26 10:06:56,230] ERROR Task cassandra_sinktemperature-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:148)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:457)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:251)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:180)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2017-09-26 10:06:56,230] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:149)
[2017-09-26 10:06:56,230] INFO Stopping Cassandra sink. (com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkTask:77)
[2017-09-26 10:06:56,230] INFO Shutting down Cassandra driver session and cluster. (com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter:183)
```

**Comment by andrewstevenson** [comment]
@joanna- The default converter is Bytes, since 0.2.6 there's been configuration changes. Please check the latest docs and READM.md for the changes.

You need to set the converter in the kql statement now. 

``INSERT INTO kjson SELECT * FROM /mjson WITHCONVERTER=com.datamountaineer.streamreactor.connect.converters.source.JsonSimpleConverter``

**Comment by joanna-** [comment]
Thank you a lot for such a quick answer! It works now perfectly, I should check it better. 

I believe you should update the first paragraph under "Feature section" in http://docs.datamountaineer.com/en/latest/mqtt.html . It still mentions "connect.mqtt.converters" property.

Thank you again.
