### ISSUE TITLE
Cassandra sink unable to consume Avro map type

### ISSUE THREAD

**Issue by comdw** [datamountaineer/stream-reactor#294]
I couldn't find any documentation to suggest this isn't supported but I get the following error message when the connector tries to obtain a message form the topic:
```
ERROR There was an error inserting the records A KCQL error occurred.Can't select an element from an array(schema:Schema{MAP}) (com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter)
java.lang.IllegalArgumentException: A KCQL error occurred.Can't select an element from an array(schema:Schema{MAP})
	at com.datamountaineer.streamreactor.connect.converters.Transform$.raiseException$1(Transform.scala:39)
	at com.datamountaineer.streamreactor.connect.converters.Transform$.apply(Transform.scala:82)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$4$$anonfun$apply$3$$anonfun$apply$1.apply$mcV$sp(CassandraJsonWriter.scala:145)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$4$$anonfun$apply$3$$anonfun$apply$1.apply(CassandraJsonWriter.scala:144)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$4$$anonfun$apply$3$$anonfun$apply$1.apply(CassandraJsonWriter.scala:144)
	at com.datamountaineer.streamreactor.connect.concurrent.ExecutorExtension$RunnableWrapper$$anon$1.run(ExecutorExtension.scala:30)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Avro schema:
```
{
	"type": "record",
	"name": "myrecord",
	"namespace": "default",
	"fields": [{
			"name": "Id",
			"type": "int"
		}, {
			"name": "Fields",
			"type": {
				"type": "map",
				"values": "string"
			}
		}
	]
}
```

Cassandra table:
`CREATE TABLE myrecord (id int, fields map<text, text>, PRIMARY KEY (id)) ;`

Example JSON record (works with Cassandra INSERT ... JSON and kafka avro console producer with the schema above):
`{"Id":1,"Fields":{"key1":"value1","key2":"value2","key3":"value3"}}`

I'm using [kafka-connect-cassandra-0.3.0-3.3.0-all.tar.gz](https://github.com/datamountaineer/stream-reactor/releases/download/0.3.0/kafka-connect-cassandra-0.3.0-3.3.0-all.tar.gz) within kafka-connect-cassandra docker container.

**Comment by stheppi** [comment]
@comdw  yes kcql does not allow selecting specific field from a map yet.
what's your kcql syntax?

**Comment by comdw** [comment]
I'm not trying to select a specific field from the map - just the whole map as that what matches the Cassandra schema.  KQCL:
`INSERT INTO myrecord SELECT * FROM mytopic`

**Comment by andrewstevenson** [comment]
this needs a fix in `avro-sql` coming in from Landoops repos. We can have a look but it'll be a few days before we get to it.

**Comment by comdw** [comment]
OK.  As a workaround I've been able to relax my Avro schema to use a standard string to pass the JSON map (without having to change Cassandra schema).  Not ideal though as it weakens my Avro schema specification.

By the way, I also noticed nullable types in Avro e.g. `{"name":"NullableLong","type":["null","long"]}` cause problems but at the producer.  Similar story as above or different issue?

**Comment by alfredo-gimenez** [comment]
Having the exact same issue here, and unfortunately can't use the workaround. Any updates?

**Comment by andrewstevenson** [comment]
We need to update the underlying avro-sql and json-sql libraries. I think it will be a month or so be for we have time, We do accept Pull requets, maybe @stheppi can point you to the right spot?

**Comment by alfredo-gimenez** [comment]
I've since come up with another hacky solution :) I modified Kafka's AvroConverter to convert map fields to strings internally, and register maps as strings in the connect schema. I would appreciate the pointers to where to implement a proper fix but can't promise anything yet. Thanks!

**Comment by provpup** [comment]
@alfredo-gimenez , can you share with me the code for your hacky solution?  I'm seeing the same issue with the Cassandra sink connector, too.  Thanks!

**Comment by alfredo-gimenez** [comment]
@provpup I do essentially the same thing as @comdw but in my custom source. When reading in a map type element, I convert it to a string before creating the `SourceRecord` that gets published to the stream. The schema-registry therefore sees a string, but it inserts correctly into Cassandra as a map (as long as that Cassandra column is of the right map schema).

**Comment by alfredo-gimenez** [comment]
@provpup See here for details: https://github.com/LLNL/nfs-directory-source/commit/8e5e7a17552d504fc65c92e1267065f1859d7f80#diff-60bd5300062d35262975c2fd7fb94503

**Comment by provpup** [comment]
Thanks @alfredo-gimenez !

**Comment by neerajk22** [comment]
Cassandra sink connector : how to add whole topic JSON as it is into single cassandra table column

I am using Cassandra Sink Connector with Kafka, now i want to insert whole topic JSON as it is into single Cassandra table column instead of creating diff cols. so what should be the connector KCQL expression ?

INSERT INTO connector_json_table SELECT * as message FROM test-nk-29-dec

test-nk-29-dec is topic name
connector_json_table is Cassandra Table name

connector_json_table contains only one single column with "Text type", Now i want to insert complete JSON into this col

**Comment by neerajk22** [comment]
**Cassandra sink connector : Not able to auto generate Cassandra table based on Avro schema**

I am using cassandra sink connector (by lensesio), not able to find any option to auto generate table structure based on Kafka topic schema (Avro schema), As my avro schema contains 50+ fields so it will be very complex to create cassandra table manually, so finding a auto generated way to create cassandra table structure. please suggest better way for same.

**Comment by neerajk22** [comment]
Facing same issue -> 
A KCQL error occurred.Can't flatten from schema:Schema{ARRAY} by selecting "field name here"
is it not supported by  cassandra sink connector (by lenses.io) ?
