### ISSUE TITLE
Cannot start kafka-connect-redis sink 

### ISSUE THREAD

**Issue by nareshds** [datamountaineer/stream-reactor#312]
Hi,
I have a problem when starting the kafka-connect-redis sink, I get the following error stack:

`[2017-11-01 15:00:18,276] INFO Sink task WorkerSinkTask{id=redis-sink-1-0} finished initialization and start (org.apache.kafka.connect.runtime.WorkerSinkTask:233)
[2017-11-01 15:00:18,399] WARN Error while fetching metadata with correlation id 2 : {my-redis-topic=LEADER_NOT_AVAILABLE} (org.apache.kafka.clients.NetworkClient:846)
[2017-11-01 15:00:18,403] INFO Discovered coordinator localhost:9092 (id: 2147483647 rack: null) for group connect-redis-sink-1. (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:597)
[2017-11-01 15:00:18,407] INFO Revoking previously assigned partitions [] for group connect-redis-sink-1 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:419)
[2017-11-01 15:00:18,407] INFO (Re-)joining group connect-redis-sink-1 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:432)
[2017-11-01 15:00:18,529] INFO Successfully joined group connect-redis-sink-1 with generation 1 (org.apache.kafka.clients.consumer.internals.AbstractCoordinator:399)
[2017-11-01 15:00:18,529] INFO Setting newly assigned partitions [my-redis-topic-0] for group connect-redis-sink-1 (org.apache.kafka.clients.consumer.internals.ConsumerCoordinator:262)
[2017-11-01 15:01:01,986] ERROR Task redis-sink-1-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask:455)
java.lang.IllegalArgumentException: requirement failed: Writer is not set!
	at scala.Predef$.require(Predef.scala:224)
	at com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask.put(RedisSinkTask.scala:90)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:435)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:251)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:180)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2017-11-01 15:01:01,987] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerSinkTask:456)
[2017-11-01 15:01:01,988] ERROR Task redis-sink-1-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:148)
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:457)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:251)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:180)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:148)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2017-11-01 15:01:01,988] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:149)
[2017-11-01 15:01:01,988] INFO Stopping Redis sink. (com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkTask:104)`

Here is my classpath:
/home/username/stream-reactor/stream-reactor-0.3.0-3.3.0/libs/kafka-connect-redis-0.3.0-3.3.0-all.jar,
/home/username/stream-reactor/stream-reactor-0.3.0-3.3.0/bin/kafka-connect-cli-1.0.2-all.jar,/home/username/confluent/confluent-3.3.0/share/java/confluent-common/* ,
/home/username/confluent/confluent-3.3.0/share/java/kafka-serde-tools/* ,
/home/username/confluent/confluent-3.3.0/share/java/monitoring-interceptors/* ,
/home/username/confluent/confluent-3.3.0/share/java/kafka/* ,
/home/username/confluent/confluent-3.3.0/share/java/confluent-support-metrics/*

I am using stream-reactor-0.3.0 with confluent 3.3.0 and running confluent in distributed mode without docker

Is there something wrong in my environment setings? Please help. Thanks

**Comment by andrewstevenson** [comment]
We need more info, which is why we added the template to the issues tracker. Please provide the start up logs of the connector and your configuration.

**Comment by nareshds** [comment]
I have attached the connector logs and below are the sink-properties I gave
`connect.progress.enabled=true
name=redis-sink-1
connect.redis.host=localhost
connect.redis.port=6379
#key.converter.schema.registry.url=http://localhost:8081
#value.converter.schema.registry.url=http://localhost:8081
connector.class=com.datamountaineer.streamreactor.connect.redis.sink.RedisSinkConnector
tasks.max=1
topics=my-redis-topic
connect.redis.kcql=INSERT INTO TABLE1 SELECT * FROM my-redis-topic`

[connect.stdout.txt](https://github.com/datamountaineer/stream-reactor/files/1433982/connect.stdout.txt)

Thanks

**Comment by nareshds** [comment]
I could resolve the issue by changing the kcql in redis sink properties from
`connect.redis.kcql=INSERT INTO TABLE1 SELECT * FROM my-redis-topic`
to
`connect.redis.kcql=INSERT INTO TABLE1 SELECT * FROM my-redis-topic PK <key>`
as suggested for the issue [208](https://github.com/datamountaineer/stream-reactor/issues/208)
