### ISSUE TITLE
NoSuchMethodError (kafka-connect-hbase)

### ISSUE THREAD

**Issue by cretok** [datamountaineer/stream-reactor#41]
Hello, I got this NoSuchMethodError message when I ran connector in standalone mode with hbase-sink.properties.
I installed kafka version 0.9 on my local.
As you see error message, "subscribe(java.util.List<java.lang.String> topics, ConsumerRebalanceListener listener)" method is possible on 0.9 version.
But datamountaineer kafka connector is dependent with 0.10 version.

Should I upgrade my kafka version to 0.10?
If I still want to use the 0.9 version, how can I modify the configuration?

`Error message during running connector`

[2016-08-16 17:54:23,913] **INFO Kafka version : 0.10.0.0** (org.apache.kafka.common.utils.AppInfoParser:83)
[2016-08-16 17:54:23,913] INFO Kafka commitId : b8642491e78c5a13 (org.apache.kafka.common.utils.AppInfoParser:84)
[2016-08-16 17:54:23,915] INFO Created connector person-hbase-test (org.apache.kafka.connect.cli.ConnectStandalone:82)
[2016-08-16 17:54:23,916] **ERROR Thread WorkerSinkTask-person-hbase-test-0 exiting with uncaught exception:  (org.apache.kafka.connect.util.ShutdownableThread:84)
java.lang.NoSuchMethodError:** org.apache.kafka.clients.consumer.KafkaConsumer.subscribe(Ljava/util/List;Lorg/apache/kafka/clients/consumer/ConsumerRebalanceListener;)V
        at org.apache.kafka.connect.runtime.WorkerSinkTask.joinConsumerGroupAndStart(WorkerSinkTask.java:143)
        at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.execute(WorkerSinkTaskThread.java:54)
        at org.apache.kafka.connect.util.ShutdownableThread.run(ShutdownableThread.java:82)
Exception in thread "WorkerSinkTask-person-hbase-test-0" java.lang.NoSuchMethodError: org.apache.kafka.clients.consumer.KafkaConsumer.subscribe(Ljava/util/List;Lorg/apache/kafka/clients/consumer/ConsumerRebalanceListener;)V
        at org.apache.kafka.connect.runtime.WorkerSinkTask.joinConsumerGroupAndStart(WorkerSinkTask.java:143)
        at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.execute(WorkerSinkTaskThread.java:54)
        at org.apache.kafka.connect.util.ShutdownableThread.run(ShutdownableThread.java:82)

**Comment by stheppi** [comment]
Hi,
 Please follow the instructions here: https://github.com/datamountaineer/docs/blob/master/source/hbase.rst

Please follow the dependencies and use the cp-2.0.1 branch to  build the assemblies. 

The cp-3.0.0 branch is linked to Confluent 3.0 version and hence the Kafka 0.10 dependency.. I would advise if possible to migrate to Confluent 3.0 version.

**Comment by stheppi** [comment]
I am going to close the ticket since is a misuse of code version.

**Comment by andrewstevenson** [comment]
I'm in the process of upgrading the docs as they still pointing to cp-2.0.1

**Comment by cretok** [comment]
I'm new to gradle, could you explain in more detail?
Here's what I did.
1) I deleted the "/root/.gradle/caches" files all.
2) I edited the kafkaVersion, confluentVersion of build.gradle file.
3) ./gradlew fatJarNoTest
But still same error occurs.
I want to remain cp version 2.0.1, so please tell me how to run on cp 2.0.1

**Comment by andrewstevenson** [comment]
Checkout master and gradle clean fatJar.

Master is on confluent 2.0.1 and kafka 0.9
________________________________

**Comment by andrewstevenson** [comment]
There's also a cp-2.0.1 branch
________________________________
From: Andrew Stevenson<mailto:andrew@datamountaineer.com>
Sent: ‎17/‎08/‎2016 07:59
To: datamountaineer/stream-reactor<mailto:reply@reply.github.com>; datamountaineer/stream-reactor<mailto:stream-reactor@noreply.github.com>
Cc: Comment<mailto:comment@noreply.github.com>
Subject: RE: [datamountaineer/stream-reactor] NoSuchMethodError (kafka-connect-hbase) (#41)

Checkout master and gradle clean fatJar.

Master is on confluent 2.0.1 and kafka 0.9
________________________________
