### ISSUE TITLE
Detected Guava issue #1635. 

### ISSUE THREAD

**Issue by ErdtR** [datamountaineer/stream-reactor#75]
Hello, I have a problem with kafka-connect-cassandra. With Confluent Platform 3.0.0 it`s work just fine. But I have a problem with CP 3.0.1. I know there were a pull request #73 that tried to fix it but it doesn't work for me. There are logs:

<pre>
 <code>[2016-10-20 17:09:30,883] INFO 
    ____        __        __  ___                  __        _
   / __ \____ _/ /_____ _/  |/  /___  __  ______  / /_____ _(_)___  ___  ___  _____
  / / / / __ `/ __/ __ `/ /|_/ / __ \/ / / / __ \/ __/ __ `/ / __ \/ _ \/ _ \/ ___/
 / /_/ / /_/ / /_/ /_/ / /  / / /_/ / /_/ / / / / /_/ /_/ / / / / /  __/  __/ /
/_____/\__,_/\__/\__,_/_/  /_/\____/\__,_/_/ /_/\__/\__,_/_/_/ /_/\___/\___/_/
       ______                                __           _____ _       __
      / ____/___ _______________ _____  ____/ /________ _/ ___/(_)___  / /__
     / /   / __ `/ ___/ ___/ __ `/ __ \/ __  / ___/ __ `/\__ \/ / __ \/ //_/
    / /___/ /_/ (__  |__  ) /_/ / / / / /_/ / /  / /_/ /___/ / / / / / ,<
    \____/\__,_/____/____/\__,_/_/ /_/\__,_/_/   \__,_//____/_/_/ /_/_/|_|

 By Andrew Stevenson. (com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkTask:64)
[2016-10-20 17:09:30,957] ERROR Task cassandra-drones-path-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
java.lang.ExceptionInInitializerError
	at com.datamountaineer.streamreactor.connect.cassandra.CassandraConnection$.getCluster(CassandraConnection.scala:43)
	at com.datamountaineer.streamreactor.connect.cassandra.CassandraConnection$.apply(CassandraConnection.scala:33)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraWriter$$anonfun$1.apply(CassandraWriter.scala:33)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraWriter$$anonfun$1.apply(CassandraWriter.scala:33)
	at scala.util.Try$.apply(Try.scala:192)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraWriter$.apply(CassandraWriter.scala:33)
	at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkTask.start(CassandraSinkTask.scala:78)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:207)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:139)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Detected Guava issue #1635 which indicates that a version of Guava less than 16.01 is in use.  This introduces codec resolution issues and potentially other incompatibility issues in the driver.  Please upgrade to Guava 16.01 or later.
	at com.datastax.driver.core.SanityChecks.checkGuava(SanityChecks.java:62)
	at com.datastax.driver.core.SanityChecks.check(SanityChecks.java:36)
	at com.datastax.driver.core.Cluster.<clinit>(Cluster.java:68)
	... 16 more
[2016-10-20 17:09:30,961] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:143)
</code>
</pre>

**Comment by ErdtR** [comment]
Hi, it's interesting that the last version of kafka-connect-cassandra  works fine with Confluent Platform 3.0.0, but doesn't work with Confluent Platform 3.0.1 even after last commit. Maybe it's a problem in Confluent 3.0.1.

**Comment by andrewstevenson** [comment]
Which version of Cassandra are you on? We are pulling in guava 16.0.1 from Cassandra

\--- com.datastax.cassandra:cassandra-driver-core:3.0.0
     +--- io.netty:netty-handler:4.0.33.Final
     |    +--- io.netty:netty-buffer:4.0.33.Final
     |    |    \--- io.netty:netty-common:4.0.33.Final
     |    +--- io.netty:netty-transport:4.0.33.Final
     |    |    \--- io.netty:netty-buffer:4.0.33.Final (*)
     |    \--- io.netty:netty-codec:4.0.33.Final
     |         \--- io.netty:netty-transport:4.0.33.Final (*)
     +--- com.google.guava:guava:16.0.1
     \--- io.dropwizard.metrics:metrics-core:3.1.2
          \--- org.slf4j:slf4j-api:1.7.7 -> 1.7.21

(*) - dependencies omitted (listed previously)

BUILD SUCCESSFUL

Total time: 6.226 secs

**Comment by ErdtR** [comment]
I use Cassandra 3.6.

**Comment by andrewstevenson** [comment]
Do you have any other connectors on the classpath like HBase?

**Comment by ErdtR** [comment]
No, I use only Cassandra connector

**Comment by andrewstevenson** [comment]
How are you starting Connect and setting the classpath?

**Comment by ErdtR** [comment]
I just put `kafka-connect-cassandra-0.2-3.0.1-all.jar` to `/usr/share/java/kafka` and run connector by command 

`connect-distributed /etc/schema-registry/connect-avro-distributed.properties`

After that when I try to create connector by CLI I get error about Guava version.

**Comment by ErdtR** [comment]
I've just fixed it. The problem was that Guava load not from `kafka-connect-cassandra-0.2-3.0.1-all.jar` but from `hive-exec-1.2.1.jar` in `/usr/share/java/kafka-connect-hdfs`. It was not a problem of Connector.

**Comment by andrewstevenson** [comment]
Great.

**Comment by andrewstevenson** [comment]
Try export CLASSPATH=kafka-connect-cassandra-0.2-3.0.1-all.jar

Then start Connect. There maybe another guava getting on the classpath first.
________________________________

**Comment by andrewstevenson** [comment]
I have it running with 3.0.1.
