### ISSUE TITLE
Cannot start kafka-connect-elastic

### ISSUE THREAD

**Issue by treziac** [datamountaineer/stream-reactor#77]
Hi,

I have a problem when starting the kafka-connect-elastic sink,I get the following stack:

```
[2016-10-24 16:35:19,896] INFO Kafka version : 0.10.0.1-cp1 (org.apache.kafka.common.utils.AppInfoParser:83)
[2016-10-24 16:35:19,896] INFO Kafka commitId : ea5fcd28195f168b (org.apache.kafka.common.utils.AppInfoParser:84)
[2016-10-24 16:35:19,898] INFO Finished starting connectors and tasks (org.apache.kafka.connect.runtime.distributed.DistributedHerder:769)
[2016-10-24 16:35:19,923] INFO

    ____        __        __  ___                  __        _
   / __ \____ _/ /_____ _/  |/  /___  __  ______  / /_____ _(_)___  ___  ___  _____
  / / / / __ `/ __/ __ `/ /|_/ / __ \/ / / / __ \/ __/ __ `/ / __ \/ _ \/ _ \/ ___/
 / /_/ / /_/ / /_/ /_/ / /  / / /_/ / /_/ / / / / /_/ /_/ / / / / /  __/  __/ /
/_____/\__,_/\__/\__,_/_/  /_/\____/\__,_/_/ /_/\__/\__,_/_/_/ /_/\___/\___/_/
       ________           __  _      _____ _       __
      / ____/ /___ ______/ /_(_)____/ ___/(_)___  / /__
     / __/ / / __ `/ ___/ __/ / ___/\__ \/ / __ \/ //_/
    / /___/ / /_/ (__  ) /_/ / /__ ___/ / / / / / ,<
   /_____/_/\__,_/____/\__/_/\___//____/_/_/ /_/_/|_|


by Andrew Stevenson
       (com.datamountaineer.streamreactor.connect.elastic.ElasticSinkTask:36)
[2016-10-24 16:35:19,927] INFO ElasticSinkConfig values:
        connect.elastic.url = localhost:9200
        connect.elastic.url.prefix = elasticsearch
        connect.elastic.cluster.name = elastic-test
        connect.elastic.export.route.query = INSERT INTO kafka_test SELECT * FROM testTopic
 (com.datamountaineer.streamreactor.connect.elastic.config.ElasticSinkConfig:178)
[2016-10-24 16:35:20,211] INFO [Baron Brimstone] loaded [], sites [] (org.elasticsearch.plugins:149)

[2016-10-24 16:35:21,302] ERROR Task elastic-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
java.lang.VerifyError: (class: org/jboss/netty/channel/socket/nio/NioWorkerPool, method: newWorker signature: (Ljava/util/concurrent/Executor;)Lorg/jboss/netty/channel/socket/nio/AbstractNioWorker;) Wrong return type in function
        at org.elasticsearch.transport.netty.NettyTransport.createClientBootstrap(NettyTransport.java:349)
        at org.elasticsearch.transport.netty.NettyTransport.doStart(NettyTransport.java:277)
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
        at org.elasticsearch.transport.TransportService.doStart(TransportService.java:170)
        at org.elasticsearch.common.component.AbstractLifecycleComponent.start(AbstractLifecycleComponent.java:68)
        at org.elasticsearch.client.transport.TransportClient$Builder.build(TransportClient.java:159)
        at com.sksamuel.elastic4s.ElasticClient$.transport(ElasticClient.scala:98)
        at com.datamountaineer.streamreactor.connect.elastic.ElasticWriter$.apply(ElasticWriter.scala:43)
        at com.datamountaineer.streamreactor.connect.elastic.ElasticSinkTask.start(ElasticSinkTask.scala:56)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:207)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:139)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[2016-10-24 16:35:21,304] ERROR Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:143)
[2016-10-24 16:35:21,304] INFO Stopping Elastic sink. (com.datamountaineer.streamreactor.connect.elastic.ElasticSinkTask:71)

```

I use the kafka-connect-elastic-0.2-3.0.0-all token from github release and a standard confluent platform 3.0.1-2.11 install, with kafka-connect-cli-0.5
elastic connector is in share/java

here is my classpath:
/opt/confluent-3.0.1/share/java/confluent-common/*
/opt/confluent-3.0.1/share/java/kafka-serde-tools/*
/opt/confluent-3.0.1/share/java/monitoring-interceptors/*
/opt/confluent-3.0.1/share/java/kafka-connect-elastic-datamountainer/*
/opt/confluent-3.0.1/bin/../share/java/kafka/*
/opt/confluent-3.0.1/bin/../share/java/confluent-support-metrics/*
/usr/share/java/confluent-support-metrics/*

Is there something wrong on my env or is the package on github invalid?

**Comment by andrewstevenson** [comment]
export CLASSPATH= kafka-connect-elastic-0.2-3.0.0-all.jar 

This will put the Connector jar first on the classpath.

**Comment by treziac** [comment]
Thanks, working better :)

**Comment by andrewstevenson** [comment]
Export CLASSPATH=kafka-connect-elastic-0.2-3.0.0.jar

Then start connect. Theres a version clash in netty. This way the connector is first on rhe classpath and should work.

We have slack channel for more direct communication.
________________________________
