### ISSUE TITLE
Druid Connector Example

### ISSUE THREAD

**Issue by mtolman** [datamountaineer/stream-reactor#86]
Hi, I'm wanting to try out your Druid Connector document here: http://docs.datamountaineer.com/en/latest/druid.html

The documentation mentions using a "druid-sink.properties" file. Do you have an example of what that file would look like?

Thanks,
Mike

**Comment by stheppi** [comment]
Hi, looks like we are missing a sample of that properties file. We will have to add one. Will make one available in the next couple of days. I hope is ok.

**Comment by andrewstevenson** [comment]
@mtolman  Try this 

name=druid-sink
connector.class=com.datamountaineer.streamreactor.connect.druid.DruidSinkConnector
connect.druid.sink.datasource.name=my_druid_datasource
connect.druid.sink.config.file=my_druid_config_file
connect.druid.sink.fields=my_field_1=my_field1,my_field_2=my_field2

**Comment by mtolman** [comment]
Thank you. I will give this a try. I was thinking that the DruidSinkConnector would be available with the docker image from this url:  http://www.landoop.com/devops/docker-solutions/
Is it not in there?
I've also tried compiling it manually, but haven't had any luck. I always get this error when running gradle:  No value has been specified for property 'zincClasspath'.

Any ideas?

**Comment by Antwnis** [comment]
Hi Mike,

I'm Antonios (from Landoop) and we had issues with DruidConnector
jars/dependency tree once it was mixed with ~14 other connectors and JVM
library at particular versions etc :-) ( i.e. we want our kafka-connect
cluster to write into cassandra + elastic + redis + influx + hdfs + ...

So we had to de-scope druid at that point. Given that there is interest
around it - we could review if we can safely add it back into the classpath
- after reviewing all dependencies etc)

Thanks, Antonios

**Comment by mtolman** [comment]
@andrewstevenson 
I was finally able to get the druid sink connector to do the gradle compile (it worked on Windows).
I tried using the sample config and found I needed to add a couple of entries:

connnect.druid.sink.write.timeout=600
topics=my_topic

After adding those, the sink task seems to start and try to do something, but it immediately fails with this error:

`[2016-12-02 20:08:27,063] ERROR Task druid-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:142)
java.lang.NullPointerException: Non-null input required
        at com.metamx.common.scala.untyped$.throwNPE(untyped.scala:117)
        at com.metamx.common.scala.untyped$.dict$default$2(untyped.scala:45)
        at com.metamx.tranquility.config.TranquilityConfig$$anonfun$2$$anonfun$apply$2.apply(TranquilityConfig.scala:63)
        at com.metamx.tranquility.config.TranquilityConfig$$anonfun$2$$anonfun$apply$2.apply(TranquilityConfig.scala:63)
        at com.metamx.common.scala.Predef$NullOps.mapNull(Predef.scala:36)
        at com.metamx.common.scala.untyped$.dict(untyped.scala:46)
        at com.metamx.tranquility.config.TranquilityConfig$$anonfun$2.apply(TranquilityConfig.scala:63)
        at com.metamx.tranquility.config.TranquilityConfig$$anonfun$2.apply(TranquilityConfig.scala:62)
        at com.metamx.common.scala.Predef$FinallyOps$$anonfun$withFinally$1.apply(Predef.scala:56)
        at com.metamx.common.scala.Predef$FinallyOps$$anonfun$withFinally$1.apply(Predef.scala:56)
        at com.metamx.tranquility.config.TranquilityConfig$.read(TranquilityConfig.scala:62)
        at com.metamx.tranquility.config.TranquilityConfig$.read(TranquilityConfig.scala:93)
        at com.datamountaineer.streamreactor.connect.druid.writer.DruidDbWriter$.apply(DruidDbWriter.scala:76)
        at com.datamountaineer.streamreactor.connect.druid.DruidSinkTask.start(DruidSinkTask.scala:63)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:207)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:139)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
`

I'm guessing I'm still missing some configuration. What should the contents of my_druid_config_file be?

**Comment by andrewstevenson** [comment]
@mtolman  I'll have a look tonight.

**Comment by andrewstevenson** [comment]
@mtolman I suspect it's reading an empty Druid config file in `connect.druid.sink.config.file=my_druid_config_file`

**Comment by andrewstevenson** [comment]
@mtolman I've just put a check in place for this.

**Comment by andrewstevenson** [comment]
@mtolman How did you get on with this?
