### ISSUE TITLE
Failed to bind port 9042 on 127.0.0.1

### ISSUE THREAD

**Issue by alparslanuysal** [datamountaineer/stream-reactor#87]
When i type the gradle test in the stream-reactor directory.It shows an error;

2016-12-01 18:42:13,808 ERROR [pool-2-thread-1] [service.StartupChecks] [execute:153] cassandra.jmx.local.port missing from cassandra-env.sh, unable to start local JMX service.
TestCassandraReaderIncr:
Exception (java.lang.IllegalStateException) encountered during startup: Failed to bind port 9042 on 127.0.0.1.
java.lang.IllegalStateException: Failed to bind port 9042 on 127.0.0.1.
        at org.apache.cassandra.transport.Server.run(Server.java:189)
        at org.apache.cassandra.transport.Server.start(Server.java:122)
        at org.apache.cassandra.service.CassandraDaemon.start(CassandraDaemon.java:430)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:531)
        at org.cassandraunit.utils.EmbeddedCassandraServerHelper$1.run(EmbeddedCassandraServerHelper.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2016-12-01 18:42:22,889 ERROR [pool-2-thread-1] [service.CassandraDaemon] [exitOrFail:638] Exception encountered during startup
java.lang.IllegalStateException: Failed to bind port 9042 on 127.0.0.1.
        at org.apache.cassandra.transport.Server.run(Server.java:189)
        at org.apache.cassandra.transport.Server.start(Server.java:122)
        at org.apache.cassandra.service.CassandraDaemon.start(CassandraDaemon.java:430)
        at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:531)
        at org.cassandraunit.utils.EmbeddedCassandraServerHelper$1.run(EmbeddedCassandraServerHelper.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
:kafka-connect-cassandra:test FAILED

FAILURE: Build failed with an exception.

**Comment by andrewstevenson** [comment]
Are you building from master?

Which version of gradle?

Do you have Cassandra already running on the you machine?

**Comment by andrewstevenson** [comment]
@alparslanuysal Did you get this resolved?

**Comment by alparslanuysal** [comment]
Hi, Gradle version:3.2.1 and yes i'm building from master.First, I tried to build when cassandra running on the machine and then stopped cassandra but, build failed again

**Comment by andrewstevenson** [comment]
Are you sure cassandra is stopped? Sometimes I've set an unclean shutdown can test failures. Anything active on port 9042?

**Comment by alparslanuysal** [comment]
I have build again and it says successful.However, I faced some logs multiple times:


2016-12-05 17:23:54,625 ERROR [ScalaTest-1-running-TestCassandraJsonWriterNoop] [sink.CassandraJsonWriter] [handleTry:46] Encountered error All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.DriverException: Error preparing query, got ERROR INVALID: unconfigured table sink_test))
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.DriverException: Error preparing query, got ERROR INVALID: unconfigured table sink_test))
        at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:84)
        at com.datastax.driver.core.exceptions.NoHostAvailableException.copy(NoHostAvailableException.java:37)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
        at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:63)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$3$$anonfun$apply$1.apply$mcV$sp(CassandraJsonWriter.scala:131)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$3$$anonfun$apply$1.apply(CassandraJsonWriter.scala:126)
        at com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraJsonWriter$$anonfun$3$$anonfun$apply$1.apply(CassandraJsonWriter.scala:126)
        at com.datamountaineer.streamreactor.connect.concurrent.ExecutorExtension$RunnableWrapper$$anon$1.run(ExecutorExtension.scala:30)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Is it OK?

**Comment by andrewstevenson** [comment]
That’s testing the recovery policies of the sinks. We intentionalyl cause a failure with the policy set to retry and let the sink recover.

**Comment by alparslanuysal** [comment]
Ok, Thanks
