### ISSUE TITLE
[Blockchain] Failed to serialize offset data

### ISSUE THREAD

**Issue by jhecking** [datamountaineer/stream-reactor#89]
I'm getting serialisation errors while running the blockchain source connector in standalone mode. The connector still produces data that I can read successfully with another Connect sink connector. But I'm seeing the following `NullPointerException`s while the offset is being committed:

```
[2016-12-06 09:19:18,292] INFO Kafka version : 0.10.1.0 (org.apache.kafka.common.utils.AppInfoParser:83)
[2016-12-06 09:19:18,292] INFO Kafka commitId : 3402a74efb23d1d4 (org.apache.kafka.common.utils.AppInfoParser:84)
[2016-12-06 09:19:18,294] INFO Created connector blockchain-source (org.apache.kafka.connect.cli.ConnectStandalone:93)
[2016-12-06 09:19:18,305] INFO
  ____        _        __  __                   _        _
 |  _ \  __ _| |_ __ _|  \/  | ___  _   _ _ __ | |_ __ _(_)_ __   ___  ___ _ __
 | | | |/ _` | __/ _` | |\/| |/ _ \| | | | '_ \| __/ _` | | '_ \ / _ \/ _ \ '__|
 | |_| | (_| | || (_| | |  | | (_) | |_| | | | | || (_| | | | | |  __/  __/ |
 |____/ \__,_|\__\__,_|_|  |_|\___/ \__,_|_| |_|\__\__,_|_|_| |_|\___|\___|_|
  ____  _            _     ____ _           _         ____ by Stefan Bocutiu
 | __ )| | ___   ___| | __/ ___| |__   __ _(_)_ __   / ___|  ___  _   _ _ __ ___ ___
 |  _ \| |/ _ \ / __| |/ / |   | '_ \ / _` | | '_ \  \___ \ / _ \| | | | '__/ __/ _ \
 | |_) | | (_) | (__|   <| |___| | | | (_| | | | | |  ___) | (_) | |_| | | | (_|  __/
 |____/|_|\___/ \___|_|\_\\____|_| |_|\__,_|_|_| |_| |____/ \___/ \__,_|_|  \___\___| (com.datamountaineer.streamreactor.connect.blockchain.source.BlockchainSourceTask:41)
[2016-12-06 09:19:18,320] INFO
Configuration for task
Map(connector.class -> com.datamountaineer.streamreactor.connect.blockchain.source.BlockchainSourceConnector, max.tasks -> 1, task.class -> com.datamountaineer.streamreactor.connect.blockchain.source.BlockchainSourceTask, name -> blockchain-source, connect.blockchain.source.kafka.topic -> blockchain)
       (com.datamountaineer.streamreactor.connect.blockchain.source.BlockchainSourceTask:42)
[2016-12-06 09:19:18,322] INFO AbstractConfig values:
	connect.blockchain.source.kafka.topic = blockchain
	connect.blockchain.source.subscription.addresses = null
	connect.blockchain.source.url = wss://ws.blockchain.info/inv
 (org.apache.kafka.common.config.AbstractConfig:180)
[2016-12-06 09:19:19,770] INFO Data manager started (com.datamountaineer.streamreactor.connect.blockchain.source.BlockchainSourceTask:57)
[2016-12-06 09:19:19,770] INFO Source task WorkerSourceTask{id=blockchain-source-0} finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask:138)
[2016-12-06 09:19:21,703] INFO Reflections took 4098 ms to scan 71 urls, producing 6430 keys and 66195 values  (org.reflections.Reflections:229)
[2016-12-06 09:20:18,293] ERROR CRITICAL: Failed to serialize offset data, making it impossible to commit offsets under namespace blockchain-source. This likely won't recover unless the unserializable partition or offset information is overwritten. (org.apache.kafka.connect.storage.OffsetStorageWriter:154)
[2016-12-06 09:20:18,293] ERROR Cause of serialization failure: (org.apache.kafka.connect.storage.OffsetStorageWriter:157)
java.lang.NullPointerException
	at org.apache.kafka.connect.storage.OffsetUtils.validateFormat(OffsetUtils.java:51)
	at org.apache.kafka.connect.storage.OffsetStorageWriter.doFlush(OffsetStorageWriter.java:142)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.commitOffsets(WorkerSourceTask.java:319)
	at org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter.commit(SourceTaskOffsetCommitter.java:107)
	at org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter.access$000(SourceTaskOffsetCommitter.java:44)
	at org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter$1.run(SourceTaskOffsetCommitter.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-06 09:20:18,295] ERROR Failed to flush org.apache.kafka.connect.runtime.WorkerSourceTask$2@32c907d2 offsets to storage:  (org.apache.kafka.connect.runtime.WorkerSourceTask:323)
java.lang.NullPointerException
	at org.apache.kafka.connect.storage.OffsetUtils.validateFormat(OffsetUtils.java:51)
	at org.apache.kafka.connect.storage.OffsetStorageWriter.doFlush(OffsetStorageWriter.java:142)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.commitOffsets(WorkerSourceTask.java:319)
	at org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter.commit(SourceTaskOffsetCommitter.java:107)
	at org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter.access$000(SourceTaskOffsetCommitter.java:44)
	at org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter$1.run(SourceTaskOffsetCommitter.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-12-06 09:20:18,295] ERROR Failed to commit offsets for WorkerSourceTask{id=blockchain-source-0} (org.apache.kafka.connect.runtime.SourceTaskOffsetCommitter:109)
```

I'm using kafka-connect-blockchain-0.2.2-3.0.1-all.jar which I've compiled from source at rev 422838acf5f08f4d7a7e5bb704be536ca2ce488e.

Here is the connector config `blockchain-source.properties`:

```
name=blockchain-source
connector.class=com.datamountaineer.streamreactor.connect.blockchain.source.BlockchainSourceConnector
max.tasks=1
connect.blockchain.source.kafka.topic = blockchain
```

And the Kafka Connect worker properties `connect-avro-standalone.properties`:

```
# Sample configuration for a standalone Kafka Connect worker that uses Avro serialization and
# integrates the the Schema Registry. This sample configuration assumes a local installation of
# Confluent Platform with all services running on their default ports.

# Bootstrap Kafka servers. If multiple servers are specified, they should be comma-separated.
bootstrap.servers=localhost:9092

# The converters specify the format of data in Kafka and how to translate it into Connect data.
# Every Connect user will need to configure these based on the format they want their data in
# when loaded from or stored into Kafka
key.converter=io.confluent.connect.avro.AvroConverter
key.converter.schema.registry.url=http://localhost:8081
value.converter=io.confluent.connect.avro.AvroConverter
value.converter.schema.registry.url=http://localhost:8081

# The internal converter used for offsets and config data is configurable and must be specified,
# but most users will always want to use the built-in default. Offset and config data is never
# visible outside of Connect in this format.
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false

# Local storage file for offset data
offset.storage.file.filename=/tmp/connect.offsets
```

**Comment by stheppi** [comment]
@jhecking  
This error baffles me. In Transaction.toSourceRecord we set the offset to be a util.Map<String, Object> with the value for the key being a Long[Collections.singletonMap("position", System.currentTimeMillis()) ] . Now connectschema#schematype should see that if you look at the code. But it doesn't and returns a null which fails in the if statement. 

I suppose you haven't changed the code for the toSourceRecord on the Transaction class (we have tested this and haven't seen it.)

You can always set null the offset in the SourceRecord since is not being used at the moment.

**Comment by jhecking** [comment]
I didn't make any changes to the source of the connector. I didn't use the latest released version just because it dumps a log statement out to the console every time poll() is called, i.e. multiple times a second.

**Comment by stheppi** [comment]
I am investigating. I will come back to you.

**Comment by jhecking** [comment]
Thanks! Please note that I was just using the blockchain connector to demo another Kafka sink connector I wrote. I'm not planning to use the blockchain connector now that the demo is done.

**Comment by stheppi** [comment]
can you try the yahoo as well? it has the same approach. I can't reproduce the error - so fix would be to make the offsets map null - the source doesn't use the offset anyway for now.

**Comment by stheppi** [comment]
removed the offsets. please use the latest

**Comment by jhecking** [comment]
Just FYI: I wasn't able to reproduce the issue with the Yahoo source connector.
