### ISSUE TITLE
Influxdb Sink Retention policy

### ISSUE THREAD

**Issue by alparslanuysal** [datamountaineer/stream-reactor#99]
Hi guys, I got retention policy error when writing avro messages to kafka.
Influx version:1.1.1

CLI output;
warning: changed `name=influxdb-sink` into `name=influx-sink`
#Connector `influx-sink`:
topics=influx-topic
name=influx-sink
connect.influx.connection.user=root
connect.influx.connection.database=mydb
tasks.max=1
connector.class=com.datamountaineer.streamreactor.connect.influx.InfluxSinkConnector
connect.influx.sink.route.query=INSERT INTO influxMeasure SELECT * FROM influx-topic WITHTIMESTAMP sys_time()
connect.influx.connection.url=http://remote:8086
connect.influx.connection.password=root
connect.influx.retention.policy=autogen
#task ids: 0

[2016-12-26 11:54:39,250] INFO Received 2 record(-s) (com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask:81)
[2016-12-26 11:54:39,327] INFO Writing ${batchPoints.getPoints.size()} to the database... (com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter:45)
[2016-12-26 11:54:39,777] ERROR Encountered error {"error":"retention policy not found: default"}
 (com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter:46)
[2016-12-26 11:54:39,785] ERROR Task influx-sink-0 threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerSinkTask:401)
java.lang.RuntimeException: java.lang.RuntimeException: {"error":"retention policy not found: default"}

	at com.datamountaineer.streamreactor.connect.errors.ThrowErrorPolicy.handle(ErrorPolicy.scala:58)
	at com.datamountaineer.streamreactor.connect.errors.ErrorHandler$class.handleError(ErrorHandler.scala:67)
	at com.datamountaineer.streamreactor.connect.errors.ErrorHandler$class.handleTry(ErrorHandler.scala:48)
	at com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter.handleTry(InfluxDbWriter.scala:30)
	at com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter.write(InfluxDbWriter.scala:48)
	at com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask$$anonfun$put$2.apply(InfluxSinkTask.scala:82)
	at com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask$$anonfun$put$2.apply(InfluxSinkTask.scala:82)
	at scala.Option.foreach(Option.scala:257)
	at com.datamountaineer.streamreactor.connect.influx.InfluxSinkTask.put(InfluxSinkTask.scala:82)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:381)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:227)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:170)
	at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:142)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:140)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: {"error":"retention policy not found: default"}

	at org.influxdb.impl.InfluxDBErrorHandler.handleError(InfluxDBErrorHandler.java:19)
	at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
	at org.influxdb.impl.$Proxy41.writePoints(Unknown Source)
	at org.influxdb.impl.InfluxDBImpl.write(InfluxDBImpl.java:151)
	at com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter$$anonfun$1.apply$mcV$sp(InfluxDbWriter.scala:46)
	at com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter$$anonfun$1.apply(InfluxDbWriter.scala:46)
	at com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter$$anonfun$1.apply(InfluxDbWriter.scala:46)
	at scala.util.Try$.apply(Try.scala:192)
	at com.datamountaineer.streamreactor.connect.influx.writers.InfluxDbWriter.write(InfluxDbWriter.scala:46)
	... 15 more

**Comment by stheppi** [comment]
@alparslanuysal 
We are preparing the 0.2.3 release. The current one 0.2.2 is working on the influxdb 0.x which was using 'default'. Best option until we make the lib available is to take the code and build it yourself. that would solve your problem

**Comment by andrewstevenson** [comment]
@alparslanuysal You can build the latest from master, we will release shortly.

**Comment by alparslanuysal** [comment]
@andrewstevenson Thanks, I will build today
